/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Wed Oct 24 15:48:43 2018. */

#include "IdentityMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t proto_router_identity_msg_fields[3] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, proto_router_identity_msg_t, UUID, UUID, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, proto_router_identity_msg_t, Token, UUID, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
