/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Wed Oct 24 15:48:44 2018. */

#include "router_gps.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const int32_t proto_router_satellite_elevation_default = -1;
const int32_t proto_router_satellite_azimuth_default = -1;
const int32_t proto_router_satellite_SNR_default = -1;
const int32_t proto_router_satellite_used_default = 0;
const uint32_t proto_router_GPS_timestamp_default = 0u;
const int32_t proto_router_GPS_latitude_default = 2000000000;
const int32_t proto_router_GPS_longitude_default = 2000000000;
const int32_t proto_router_GPS_altitude_default = 0;
const int32_t proto_router_GPS_quality_default = 0;
const int32_t proto_router_GPS_dimension_default = 0;
const int32_t proto_router_GPS_PDOP_default = 0;
const int32_t proto_router_GPS_HDOP_default = 0;
const int32_t proto_router_GPS_VDOP_default = 0;
const int32_t proto_router_GPS_used_star_default = 0;
const int32_t proto_router_GPS_view_star_default = 0;
const int32_t proto_router_GPS_horizontal_default = 0;
const int32_t proto_router_GPS_vertical_default = 0;
const int32_t proto_router_GPS_fix_time_default = 0;


const pb_field_t proto_router_g_p_s_req_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, proto_router_g_p_s_req_t, Iden, Iden, &proto_router_identity_msg_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, proto_router_g_p_s_req_t, GPSInfo, Iden, &proto_router_GPS_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_router_satellite_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, proto_router_satellite_t, ID, ID, 0),
    PB_FIELD(  2, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_satellite_t, Elevation, ID, &proto_router_satellite_elevation_default),
    PB_FIELD(  3, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_satellite_t, Azimuth, Elevation, &proto_router_satellite_azimuth_default),
    PB_FIELD(  4, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_satellite_t, SNR, Azimuth, &proto_router_satellite_SNR_default),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_satellite_t, Used, SNR, &proto_router_satellite_used_default),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, OTHER, proto_router_satellite_t, Type, Used, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_router_GPS_fields[16] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, proto_router_GPS_t, Timestamp, Timestamp, &proto_router_GPS_timestamp_default),
    PB_FIELD(  2, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Latitude, Timestamp, &proto_router_GPS_latitude_default),
    PB_FIELD(  3, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Longitude, Latitude, &proto_router_GPS_longitude_default),
    PB_FIELD(  4, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Altitude, Longitude, &proto_router_GPS_altitude_default),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Quality, Altitude, &proto_router_GPS_quality_default),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Dimension, Quality, &proto_router_GPS_dimension_default),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, PDOP, Dimension, &proto_router_GPS_PDOP_default),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, HDOP, PDOP, &proto_router_GPS_HDOP_default),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, VDOP, HDOP, &proto_router_GPS_VDOP_default),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, UsedStar, VDOP, &proto_router_GPS_used_star_default),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, ViewStar, UsedStar, &proto_router_GPS_view_star_default),
    PB_FIELD( 14, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Horizontal, ViewStar, &proto_router_GPS_horizontal_default),
    PB_FIELD( 15, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, Vertical, Horizontal, &proto_router_GPS_vertical_default),
    PB_FIELD( 16, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, FixTime, Vertical, &proto_router_GPS_fix_time_default),
    PB_FIELD( 17, MESSAGE , OPTIONAL, STATIC  , OTHER, proto_router_GPS_t, SatelliteInfo, FixTime, &proto_router_satellite_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_router_g_p_s_req_t, Iden) < 65536 && pb_membersize(proto_router_g_p_s_req_t, GPSInfo) < 65536 && pb_membersize(proto_router_GPS_t, SatelliteInfo) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_proto_router_g_p_s_req_proto_router_satellite_proto_router_GPS)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_router_g_p_s_req_t, Iden) < 256 && pb_membersize(proto_router_g_p_s_req_t, GPSInfo) < 256 && pb_membersize(proto_router_GPS_t, SatelliteInfo) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_proto_router_g_p_s_req_proto_router_satellite_proto_router_GPS)
#endif


/* @@protoc_insertion_point(eof) */
