/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Wed Oct 24 15:48:44 2018. */

#include "router_env.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t proto_router_env_timestamp_default = 0u;
const int32_t proto_router_env_battery_voltage_default = 0;
const int32_t proto_router_env_inner_temperature_default = 0;
const int32_t proto_router_env_inner_humidity_default = 0;
const int32_t proto_router_env_inner_pressure_default = 0;
const int32_t proto_router_env_ambient_light_default = 0;


const pb_field_t proto_router_env_req_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, proto_router_env_req_t, Iden, Iden, &proto_router_identity_msg_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, proto_router_env_req_t, EnvInfo, Iden, &proto_router_env_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_router_env_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, proto_router_env_t, Timestamp, Timestamp, &proto_router_env_timestamp_default),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_env_t, BatteryVoltage, Timestamp, &proto_router_env_battery_voltage_default),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, proto_router_env_t, InnerTemperature, BatteryVoltage, &proto_router_env_inner_temperature_default),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_env_t, InnerHumidity, InnerTemperature, &proto_router_env_inner_humidity_default),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_env_t, InnerPressure, InnerHumidity, &proto_router_env_inner_pressure_default),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, proto_router_env_t, AmbientLight, InnerPressure, &proto_router_env_ambient_light_default),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_router_env_req_t, Iden) < 65536 && pb_membersize(proto_router_env_req_t, EnvInfo) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_proto_router_env_req_proto_router_env)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_router_env_req_t, Iden) < 256 && pb_membersize(proto_router_env_req_t, EnvInfo) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_proto_router_env_req_proto_router_env)
#endif


/* @@protoc_insertion_point(eof) */
