/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Wed Oct 24 15:48:43 2018. */

#ifndef PB_ROUTER_EXECSTA_PB_H_INCLUDED
#define PB_ROUTER_EXECSTA_PB_H_INCLUDED
#include <pb.h>

#include "IdentityMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum
{
    PROTO_ROUTER_EXECUTE_STATE_FAILED = 0,
    PROTO_ROUTER_EXECUTE_STATE_SUCCESSED = 1,
    PROTO_ROUTER_EXECUTE_STATE_WITHOUT = 2,
    PROTO_ROUTER_EXECUTE_STATE_INVALID = 3
} proto_router_execute_state_t;
#define PROTO_ROUTER_EXECUTE_STATE_MIN PROTO_ROUTER_EXECUTE_STATE_FAILED
#define PROTO_ROUTER_EXECUTE_STATE_MAX PROTO_ROUTER_EXECUTE_STATE_INVALID
#define PROTO_ROUTER_EXECUTE_STATE_ARRAYSIZE ((proto_router_execute_state_t)(PROTO_ROUTER_EXECUTE_STATE_INVALID+1))

/* Struct definitions */
typedef struct {
    proto_router_identity_msg_t Iden;
    proto_router_execute_state_t State;
/* @@protoc_insertion_point(struct:proto_router_exec_sta_rsp_t) */
} proto_router_exec_sta_rsp_t;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PROTO_ROUTER_EXEC_STA_RSP_INIT_DEFAULT   {PROTO_ROUTER_IDENTITY_MSG_INIT_DEFAULT, (proto_router_execute_state_t)0}
#define PROTO_ROUTER_EXEC_STA_RSP_INIT_ZERO      {PROTO_ROUTER_IDENTITY_MSG_INIT_ZERO, (proto_router_execute_state_t)0}

/* Field tags (for use in manual encoding/decoding) */
#define PROTO_ROUTER_EXEC_STA_RSP_IDEN_TAG       1
#define PROTO_ROUTER_EXEC_STA_RSP_STATE_TAG      2

/* Struct field encoding specification for nanopb */
extern const pb_field_t proto_router_exec_sta_rsp_fields[3];

/* Maximum encoded size of messages (where known) */
#define PROTO_ROUTER_EXEC_STA_RSP_SIZE           (8 + PROTO_ROUTER_IDENTITY_MSG_SIZE)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ROUTER_EXECSTA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
