# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: App.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='App.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\tApp.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"A\n\x06\x41ppReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x12\n\x07\x43ommand\x18\x02 \x01(\x05:\x01\x30\"W\n\x06\x41ppRsp\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x13\n\x08LinkType\x18\x02 \x01(\x05:\x01\x30\x12\x13\n\x08WorkMode\x18\x03 \x01(\x05:\x01\x30')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_APPREQ = _descriptor.Descriptor(
  name='AppReq',
  full_name='protocol.AppReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.AppReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Command', full_name='protocol.AppReq.Command', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=107,
)


_APPRSP = _descriptor.Descriptor(
  name='AppRsp',
  full_name='protocol.AppRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.AppRsp.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LinkType', full_name='protocol.AppRsp.LinkType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WorkMode', full_name='protocol.AppRsp.WorkMode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=196,
)

_APPREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_APPRSP.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
DESCRIPTOR.message_types_by_name['AppReq'] = _APPREQ
DESCRIPTOR.message_types_by_name['AppRsp'] = _APPRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppReq = _reflection.GeneratedProtocolMessageType('AppReq', (_message.Message,), dict(
  DESCRIPTOR = _APPREQ,
  __module__ = 'App_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AppReq)
  ))
_sym_db.RegisterMessage(AppReq)

AppRsp = _reflection.GeneratedProtocolMessageType('AppRsp', (_message.Message,), dict(
  DESCRIPTOR = _APPRSP,
  __module__ = 'App_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AppRsp)
  ))
_sym_db.RegisterMessage(AppRsp)


# @@protoc_insertion_point(module_scope)
