/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Authenticator.proto */

#ifndef PROTOBUF_C_Authenticator_2eproto__INCLUDED
#define PROTOBUF_C_Authenticator_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IdentityMsg.pb-c.h"

typedef struct _Protocol__Authenticator Protocol__Authenticator;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__Authenticator
{
  ProtobufCMessage base;
  Protocol__IdentityMsg *iden;
};
#define PROTOCOL__AUTHENTICATOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__authenticator__descriptor) \
    , NULL }


/* Protocol__Authenticator methods */
void   protocol__authenticator__init
                     (Protocol__Authenticator         *message);
size_t protocol__authenticator__get_packed_size
                     (const Protocol__Authenticator   *message);
size_t protocol__authenticator__pack
                     (const Protocol__Authenticator   *message,
                      uint8_t             *out);
size_t protocol__authenticator__pack_to_buffer
                     (const Protocol__Authenticator   *message,
                      ProtobufCBuffer     *buffer);
Protocol__Authenticator *
       protocol__authenticator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__authenticator__free_unpacked
                     (Protocol__Authenticator *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__Authenticator_Closure)
                 (const Protocol__Authenticator *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__authenticator__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Authenticator_2eproto__INCLUDED */
