/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Authenticator.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Authenticator.pb-c.h"
void   protocol__authenticator__init
                     (Protocol__Authenticator         *message)
{
  static const Protocol__Authenticator init_value = PROTOCOL__AUTHENTICATOR__INIT;
  *message = init_value;
}
size_t protocol__authenticator__get_packed_size
                     (const Protocol__Authenticator *message)
{
  assert(message->base.descriptor == &protocol__authenticator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__authenticator__pack
                     (const Protocol__Authenticator *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__authenticator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__authenticator__pack_to_buffer
                     (const Protocol__Authenticator *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__authenticator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Authenticator *
       protocol__authenticator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Authenticator *)
     protobuf_c_message_unpack (&protocol__authenticator__descriptor,
                                allocator, len, data);
}
void   protocol__authenticator__free_unpacked
                     (Protocol__Authenticator *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__authenticator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__authenticator__field_descriptors[1] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__Authenticator, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__authenticator__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__authenticator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__authenticator__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Authenticator",
  "Authenticator",
  "Protocol__Authenticator",
  "protocol",
  sizeof(Protocol__Authenticator),
  1,
  protocol__authenticator__field_descriptors,
  protocol__authenticator__field_indices_by_name,
  1,  protocol__authenticator__number_ranges,
  (ProtobufCMessageInit) protocol__authenticator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
