# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Authenticator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Authenticator.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x41uthenticator.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"4\n\rAuthenticator\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_AUTHENTICATOR = _descriptor.Descriptor(
  name='Authenticator',
  full_name='protocol.Authenticator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.Authenticator.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=104,
)

_AUTHENTICATOR.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
DESCRIPTOR.message_types_by_name['Authenticator'] = _AUTHENTICATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Authenticator = _reflection.GeneratedProtocolMessageType('Authenticator', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATOR,
  __module__ = 'Authenticator_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Authenticator)
  ))
_sym_db.RegisterMessage(Authenticator)


# @@protoc_insertion_point(module_scope)
