# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Behavior.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Behavior.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x42\x65havior.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"\\\n\x0b\x42\x65haviorReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12(\n\x0c\x42\x65haviorInfo\x18\x02 \x03(\x0b\x32\x12.protocol.Behavior\"[\n\x08\x42\x65havior\x12\x14\n\tTimestamp\x18\x01 \x01(\r:\x01\x30\x12\x39\n\x04type\x18\x02 \x01(\x0e\x32\x16.protocol.BehaviorType:\x13\x42\x65haviorTypeUnknown*\xe0\x01\n\x0c\x42\x65haviorType\x12\x17\n\x13\x42\x65haviorTypeUnknown\x10\x00\x12\x13\n\x0f\x42\x65haviorTypeEat\x10\x01\x12\x1a\n\x16\x42\x65haviorTypeRumination\x10\x02\x12\x1c\n\x18\x42\x65haviorTypeActivityWeak\x10\x03\x12\x1b\n\x17\x42\x65haviorTypeActivityMid\x10\x04\x12\x1e\n\x1a\x42\x65haviorTypeActivityStrong\x10\x05\x12\x15\n\x11\x42\x65haviorTypeSleep\x10\x06\x12\x14\n\x10\x42\x65haviorTypeWalk\x10\x07')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])

_BEHAVIORTYPE = _descriptor.EnumDescriptor(
  name='BehaviorType',
  full_name='protocol.BehaviorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeUnknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeEat', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeRumination', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeActivityWeak', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeActivityMid', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeActivityStrong', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeSleep', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BehaviorTypeWalk', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=235,
  serialized_end=459,
)
_sym_db.RegisterEnumDescriptor(_BEHAVIORTYPE)

BehaviorType = enum_type_wrapper.EnumTypeWrapper(_BEHAVIORTYPE)
BehaviorTypeUnknown = 0
BehaviorTypeEat = 1
BehaviorTypeRumination = 2
BehaviorTypeActivityWeak = 3
BehaviorTypeActivityMid = 4
BehaviorTypeActivityStrong = 5
BehaviorTypeSleep = 6
BehaviorTypeWalk = 7



_BEHAVIORREQ = _descriptor.Descriptor(
  name='BehaviorReq',
  full_name='protocol.BehaviorReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.BehaviorReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BehaviorInfo', full_name='protocol.BehaviorReq.BehaviorInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=139,
)


_BEHAVIOR = _descriptor.Descriptor(
  name='Behavior',
  full_name='protocol.Behavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.Behavior.Timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protocol.Behavior.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=232,
)

_BEHAVIORREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_BEHAVIORREQ.fields_by_name['BehaviorInfo'].message_type = _BEHAVIOR
_BEHAVIOR.fields_by_name['type'].enum_type = _BEHAVIORTYPE
DESCRIPTOR.message_types_by_name['BehaviorReq'] = _BEHAVIORREQ
DESCRIPTOR.message_types_by_name['Behavior'] = _BEHAVIOR
DESCRIPTOR.enum_types_by_name['BehaviorType'] = _BEHAVIORTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BehaviorReq = _reflection.GeneratedProtocolMessageType('BehaviorReq', (_message.Message,), dict(
  DESCRIPTOR = _BEHAVIORREQ,
  __module__ = 'Behavior_pb2'
  # @@protoc_insertion_point(class_scope:protocol.BehaviorReq)
  ))
_sym_db.RegisterMessage(BehaviorReq)

Behavior = _reflection.GeneratedProtocolMessageType('Behavior', (_message.Message,), dict(
  DESCRIPTOR = _BEHAVIOR,
  __module__ = 'Behavior_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Behavior)
  ))
_sym_db.RegisterMessage(Behavior)


# @@protoc_insertion_point(module_scope)
