/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Behavior.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Behavior.pb-c.h"
void   protocol__behavior_req__init
                     (Protocol__BehaviorReq         *message)
{
  static const Protocol__BehaviorReq init_value = PROTOCOL__BEHAVIOR_REQ__INIT;
  *message = init_value;
}
size_t protocol__behavior_req__get_packed_size
                     (const Protocol__BehaviorReq *message)
{
  assert(message->base.descriptor == &protocol__behavior_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__behavior_req__pack
                     (const Protocol__BehaviorReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__behavior_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__behavior_req__pack_to_buffer
                     (const Protocol__BehaviorReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__behavior_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__BehaviorReq *
       protocol__behavior_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__BehaviorReq *)
     protobuf_c_message_unpack (&protocol__behavior_req__descriptor,
                                allocator, len, data);
}
void   protocol__behavior_req__free_unpacked
                     (Protocol__BehaviorReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__behavior_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__behavior__init
                     (Protocol__Behavior         *message)
{
  static const Protocol__Behavior init_value = PROTOCOL__BEHAVIOR__INIT;
  *message = init_value;
}
size_t protocol__behavior__get_packed_size
                     (const Protocol__Behavior *message)
{
  assert(message->base.descriptor == &protocol__behavior__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__behavior__pack
                     (const Protocol__Behavior *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__behavior__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__behavior__pack_to_buffer
                     (const Protocol__Behavior *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__behavior__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Behavior *
       protocol__behavior__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Behavior *)
     protobuf_c_message_unpack (&protocol__behavior__descriptor,
                                allocator, len, data);
}
void   protocol__behavior__free_unpacked
                     (Protocol__Behavior *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__behavior__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__behavior_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__BehaviorReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BehaviorInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__BehaviorReq, n_behaviorinfo),
    offsetof(Protocol__BehaviorReq, behaviorinfo),
    &protocol__behavior__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__behavior_req__field_indices_by_name[] = {
  1,   /* field[1] = BehaviorInfo */
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__behavior_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__behavior_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.BehaviorReq",
  "BehaviorReq",
  "Protocol__BehaviorReq",
  "protocol",
  sizeof(Protocol__BehaviorReq),
  2,
  protocol__behavior_req__field_descriptors,
  protocol__behavior_req__field_indices_by_name,
  1,  protocol__behavior_req__number_ranges,
  (ProtobufCMessageInit) protocol__behavior_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__behavior__timestamp__default_value = 0u;
static const Protocol__BehaviorType protocol__behavior__type__default_value = PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeUnknown;
static const ProtobufCFieldDescriptor protocol__behavior__field_descriptors[2] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Behavior, has_timestamp),
    offsetof(Protocol__Behavior, timestamp),
    NULL,
    &protocol__behavior__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Protocol__Behavior, has_type),
    offsetof(Protocol__Behavior, type),
    &protocol__behavior_type__descriptor,
    &protocol__behavior__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__behavior__field_indices_by_name[] = {
  0,   /* field[0] = Timestamp */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange protocol__behavior__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__behavior__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Behavior",
  "Behavior",
  "Protocol__Behavior",
  "protocol",
  sizeof(Protocol__Behavior),
  2,
  protocol__behavior__field_descriptors,
  protocol__behavior__field_indices_by_name,
  1,  protocol__behavior__number_ranges,
  (ProtobufCMessageInit) protocol__behavior__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue protocol__behavior_type__enum_values_by_number[8] =
{
  { "BehaviorTypeUnknown", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeUnknown", 0 },
  { "BehaviorTypeEat", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeEat", 1 },
  { "BehaviorTypeRumination", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeRumination", 2 },
  { "BehaviorTypeActivityWeak", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeActivityWeak", 3 },
  { "BehaviorTypeActivityMid", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeActivityMid", 4 },
  { "BehaviorTypeActivityStrong", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeActivityStrong", 5 },
  { "BehaviorTypeSleep", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeSleep", 6 },
  { "BehaviorTypeWalk", "PROTOCOL__BEHAVIOR_TYPE__BehaviorTypeWalk", 7 },
};
static const ProtobufCIntRange protocol__behavior_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex protocol__behavior_type__enum_values_by_name[8] =
{
  { "BehaviorTypeActivityMid", 4 },
  { "BehaviorTypeActivityStrong", 5 },
  { "BehaviorTypeActivityWeak", 3 },
  { "BehaviorTypeEat", 1 },
  { "BehaviorTypeRumination", 2 },
  { "BehaviorTypeSleep", 6 },
  { "BehaviorTypeUnknown", 0 },
  { "BehaviorTypeWalk", 7 },
};
const ProtobufCEnumDescriptor protocol__behavior_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "protocol.BehaviorType",
  "BehaviorType",
  "Protocol__BehaviorType",
  "protocol",
  8,
  protocol__behavior_type__enum_values_by_number,
  8,
  protocol__behavior_type__enum_values_by_name,
  1,
  protocol__behavior_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
