/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Cellular.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Cellular.pb-c.h"
void   protocol__cellular_req__init
                     (Protocol__CellularReq         *message)
{
  static const Protocol__CellularReq init_value = PROTOCOL__CELLULAR_REQ__INIT;
  *message = init_value;
}
size_t protocol__cellular_req__get_packed_size
                     (const Protocol__CellularReq *message)
{
  assert(message->base.descriptor == &protocol__cellular_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__cellular_req__pack
                     (const Protocol__CellularReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__cellular_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__cellular_req__pack_to_buffer
                     (const Protocol__CellularReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__cellular_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__CellularReq *
       protocol__cellular_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__CellularReq *)
     protobuf_c_message_unpack (&protocol__cellular_req__descriptor,
                                allocator, len, data);
}
void   protocol__cellular_req__free_unpacked
                     (Protocol__CellularReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__cellular_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__cell__init
                     (Protocol__Cell         *message)
{
  static const Protocol__Cell init_value = PROTOCOL__CELL__INIT;
  *message = init_value;
}
size_t protocol__cell__get_packed_size
                     (const Protocol__Cell *message)
{
  assert(message->base.descriptor == &protocol__cell__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__cell__pack
                     (const Protocol__Cell *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__cell__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__cell__pack_to_buffer
                     (const Protocol__Cell *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__cell__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Cell *
       protocol__cell__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Cell *)
     protobuf_c_message_unpack (&protocol__cell__descriptor,
                                allocator, len, data);
}
void   protocol__cell__free_unpacked
                     (Protocol__Cell *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__cell__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__cellular__init
                     (Protocol__Cellular         *message)
{
  static const Protocol__Cellular init_value = PROTOCOL__CELLULAR__INIT;
  *message = init_value;
}
size_t protocol__cellular__get_packed_size
                     (const Protocol__Cellular *message)
{
  assert(message->base.descriptor == &protocol__cellular__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__cellular__pack
                     (const Protocol__Cellular *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__cellular__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__cellular__pack_to_buffer
                     (const Protocol__Cellular *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__cellular__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Cellular *
       protocol__cellular__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Cellular *)
     protobuf_c_message_unpack (&protocol__cellular__descriptor,
                                allocator, len, data);
}
void   protocol__cellular__free_unpacked
                     (Protocol__Cellular *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__cellular__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__cellular_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__CellularReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CellularInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__CellularReq, n_cellularinfo),
    offsetof(Protocol__CellularReq, cellularinfo),
    &protocol__cellular__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__cellular_req__field_indices_by_name[] = {
  1,   /* field[1] = CellularInfo */
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__cellular_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__cellular_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.CellularReq",
  "CellularReq",
  "Protocol__CellularReq",
  "protocol",
  sizeof(Protocol__CellularReq),
  2,
  protocol__cellular_req__field_descriptors,
  protocol__cellular_req__field_indices_by_name,
  1,  protocol__cellular_req__number_ranges,
  (ProtobufCMessageInit) protocol__cellular_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t protocol__cell__serving__default_value = 0;
static const int32_t protocol__cell__type__default_value = 0;
static const int32_t protocol__cell__mcc__default_value = 0;
static const int32_t protocol__cell__mnc__default_value = 0;
static const int32_t protocol__cell__bsic__default_value = 0;
static const int32_t protocol__cell__lac__default_value = 0;
static const int32_t protocol__cell__tac__default_value = 0;
static const int32_t protocol__cell__arfcn__default_value = 0;
static const int32_t protocol__cell__rx_level__default_value = 99;
static const int32_t protocol__cell__rx_quality__default_value = 99;
static const int32_t protocol__cell__rssi__default_value = 99;
static const int32_t protocol__cell__phys_cell_id__default_value = 0;
static const ProtobufCFieldDescriptor protocol__cell__field_descriptors[13] =
{
  {
    "CellID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Cell, cellid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Serving",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_serving),
    offsetof(Protocol__Cell, serving),
    NULL,
    &protocol__cell__serving__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_type),
    offsetof(Protocol__Cell, type),
    NULL,
    &protocol__cell__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MCC",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_mcc),
    offsetof(Protocol__Cell, mcc),
    NULL,
    &protocol__cell__mcc__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MNC",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_mnc),
    offsetof(Protocol__Cell, mnc),
    NULL,
    &protocol__cell__mnc__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BSIC",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_bsic),
    offsetof(Protocol__Cell, bsic),
    NULL,
    &protocol__cell__bsic__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LAC",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_lac),
    offsetof(Protocol__Cell, lac),
    NULL,
    &protocol__cell__lac__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TAC",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_tac),
    offsetof(Protocol__Cell, tac),
    NULL,
    &protocol__cell__tac__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ARFCN",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_arfcn),
    offsetof(Protocol__Cell, arfcn),
    NULL,
    &protocol__cell__arfcn__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RxLevel",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Cell, has_rxlevel),
    offsetof(Protocol__Cell, rxlevel),
    NULL,
    &protocol__cell__rx_level__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RxQuality",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Cell, has_rxquality),
    offsetof(Protocol__Cell, rxquality),
    NULL,
    &protocol__cell__rx_quality__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RSSI",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Cell, has_rssi),
    offsetof(Protocol__Cell, rssi),
    NULL,
    &protocol__cell__rssi__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PhysCellID",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cell, has_physcellid),
    offsetof(Protocol__Cell, physcellid),
    NULL,
    &protocol__cell__phys_cell_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__cell__field_indices_by_name[] = {
  8,   /* field[8] = ARFCN */
  5,   /* field[5] = BSIC */
  0,   /* field[0] = CellID */
  6,   /* field[6] = LAC */
  3,   /* field[3] = MCC */
  4,   /* field[4] = MNC */
  12,   /* field[12] = PhysCellID */
  11,   /* field[11] = RSSI */
  9,   /* field[9] = RxLevel */
  10,   /* field[10] = RxQuality */
  1,   /* field[1] = Serving */
  7,   /* field[7] = TAC */
  2,   /* field[2] = Type */
};
static const ProtobufCIntRange protocol__cell__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor protocol__cell__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Cell",
  "Cell",
  "Protocol__Cell",
  "protocol",
  sizeof(Protocol__Cell),
  13,
  protocol__cell__field_descriptors,
  protocol__cell__field_indices_by_name,
  1,  protocol__cell__number_ranges,
  (ProtobufCMessageInit) protocol__cell__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__cellular__timestamp__default_value = 0u;
static const int32_t protocol__cellular__latitude__default_value = 2000000000;
static const int32_t protocol__cellular__longitude__default_value = 2000000000;
static const uint32_t protocol__cellular__error_flag__default_value = 0u;
static const uint32_t protocol__cellular__exit_flag__default_value = 0u;
static const int32_t protocol__cellular__total_time__default_value = 0;
static const int32_t protocol__cellular__hwt_time__default_value = 0;
static const int32_t protocol__cellular__sim_time__default_value = 0;
static const int32_t protocol__cellular__num_time__default_value = 0;
static const int32_t protocol__cellular__rssi_time__default_value = 0;
static const int32_t protocol__cellular__register_time__default_value = 0;
static const int32_t protocol__cellular__attach_time__default_value = 0;
static const int32_t protocol__cellular__pdp_time__default_value = 0;
static const int32_t protocol__cellular__connection_time__default_value = 0;
static const int32_t protocol__cellular__communication_time__default_value = 0;
static const int32_t protocol__cellular__sms_time__default_value = 0;
static const uint32_t protocol__cellular__network_operator__default_value = 0u;
static const int32_t protocol__cellular__signal_strength__default_value = 0;
static const int32_t protocol__cellular__bit_error_rate__default_value = 0;
static const int32_t protocol__cellular__radio_access_technology__default_value = 0;
static const int32_t protocol__cellular__temperature__default_value = 0;
static const int32_t protocol__cellular__battery_voltage__default_value = 0;
static const ProtobufCFieldDescriptor protocol__cellular__field_descriptors[23] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Cellular, has_timestamp),
    offsetof(Protocol__Cellular, timestamp),
    NULL,
    &protocol__cellular__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Latitude",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Cellular, has_latitude),
    offsetof(Protocol__Cellular, latitude),
    NULL,
    &protocol__cellular__latitude__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Longitude",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Cellular, has_longitude),
    offsetof(Protocol__Cellular, longitude),
    NULL,
    &protocol__cellular__longitude__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CellInfo",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__Cellular, n_cellinfo),
    offsetof(Protocol__Cellular, cellinfo),
    &protocol__cell__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ErrorFlag",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Cellular, has_errorflag),
    offsetof(Protocol__Cellular, errorflag),
    NULL,
    &protocol__cellular__error_flag__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ExitFlag",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Cellular, has_exitflag),
    offsetof(Protocol__Cellular, exitflag),
    NULL,
    &protocol__cellular__exit_flag__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TotalTime",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_totaltime),
    offsetof(Protocol__Cellular, totaltime),
    NULL,
    &protocol__cellular__total_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HwtTime",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_hwttime),
    offsetof(Protocol__Cellular, hwttime),
    NULL,
    &protocol__cellular__hwt_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SimTime",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_simtime),
    offsetof(Protocol__Cellular, simtime),
    NULL,
    &protocol__cellular__sim_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NumTime",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_numtime),
    offsetof(Protocol__Cellular, numtime),
    NULL,
    &protocol__cellular__num_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RssiTime",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_rssitime),
    offsetof(Protocol__Cellular, rssitime),
    NULL,
    &protocol__cellular__rssi_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RegisterTime",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_registertime),
    offsetof(Protocol__Cellular, registertime),
    NULL,
    &protocol__cellular__register_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "AttachTime",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_attachtime),
    offsetof(Protocol__Cellular, attachtime),
    NULL,
    &protocol__cellular__attach_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PdpTime",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_pdptime),
    offsetof(Protocol__Cellular, pdptime),
    NULL,
    &protocol__cellular__pdp_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ConnectionTime",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_connectiontime),
    offsetof(Protocol__Cellular, connectiontime),
    NULL,
    &protocol__cellular__connection_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CommunicationTime",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_communicationtime),
    offsetof(Protocol__Cellular, communicationtime),
    NULL,
    &protocol__cellular__communication_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SmsTime",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_smstime),
    offsetof(Protocol__Cellular, smstime),
    NULL,
    &protocol__cellular__sms_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NetworkOperator",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Cellular, has_networkoperator),
    offsetof(Protocol__Cellular, networkoperator),
    NULL,
    &protocol__cellular__network_operator__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SignalStrength",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_signalstrength),
    offsetof(Protocol__Cellular, signalstrength),
    NULL,
    &protocol__cellular__signal_strength__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BitErrorRate",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_biterrorrate),
    offsetof(Protocol__Cellular, biterrorrate),
    NULL,
    &protocol__cellular__bit_error_rate__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RadioAccessTechnology",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_radioaccesstechnology),
    offsetof(Protocol__Cellular, radioaccesstechnology),
    NULL,
    &protocol__cellular__radio_access_technology__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Temperature",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_temperature),
    offsetof(Protocol__Cellular, temperature),
    NULL,
    &protocol__cellular__temperature__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BatteryVoltage",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Cellular, has_batteryvoltage),
    offsetof(Protocol__Cellular, batteryvoltage),
    NULL,
    &protocol__cellular__battery_voltage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__cellular__field_indices_by_name[] = {
  12,   /* field[12] = AttachTime */
  22,   /* field[22] = BatteryVoltage */
  19,   /* field[19] = BitErrorRate */
  3,   /* field[3] = CellInfo */
  15,   /* field[15] = CommunicationTime */
  14,   /* field[14] = ConnectionTime */
  4,   /* field[4] = ErrorFlag */
  5,   /* field[5] = ExitFlag */
  7,   /* field[7] = HwtTime */
  1,   /* field[1] = Latitude */
  2,   /* field[2] = Longitude */
  17,   /* field[17] = NetworkOperator */
  9,   /* field[9] = NumTime */
  13,   /* field[13] = PdpTime */
  20,   /* field[20] = RadioAccessTechnology */
  11,   /* field[11] = RegisterTime */
  10,   /* field[10] = RssiTime */
  18,   /* field[18] = SignalStrength */
  8,   /* field[8] = SimTime */
  16,   /* field[16] = SmsTime */
  21,   /* field[21] = Temperature */
  0,   /* field[0] = Timestamp */
  6,   /* field[6] = TotalTime */
};
static const ProtobufCIntRange protocol__cellular__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor protocol__cellular__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Cellular",
  "Cellular",
  "Protocol__Cellular",
  "protocol",
  sizeof(Protocol__Cellular),
  23,
  protocol__cellular__field_descriptors,
  protocol__cellular__field_indices_by_name,
  1,  protocol__cellular__number_ranges,
  (ProtobufCMessageInit) protocol__cellular__init,
  NULL,NULL,NULL    /* reserved[123] */
};
