/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Debug.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Debug.pb-c.h"
void   protocol__debug_req__init
                     (Protocol__DebugReq         *message)
{
  static const Protocol__DebugReq init_value = PROTOCOL__DEBUG_REQ__INIT;
  *message = init_value;
}
size_t protocol__debug_req__get_packed_size
                     (const Protocol__DebugReq *message)
{
  assert(message->base.descriptor == &protocol__debug_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__debug_req__pack
                     (const Protocol__DebugReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__debug_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__debug_req__pack_to_buffer
                     (const Protocol__DebugReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__debug_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__DebugReq *
       protocol__debug_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__DebugReq *)
     protobuf_c_message_unpack (&protocol__debug_req__descriptor,
                                allocator, len, data);
}
void   protocol__debug_req__free_unpacked
                     (Protocol__DebugReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__debug_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__debug_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__DebugReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__DebugReq, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__debug_req__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange protocol__debug_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__debug_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.DebugReq",
  "DebugReq",
  "Protocol__DebugReq",
  "protocol",
  sizeof(Protocol__DebugReq),
  2,
  protocol__debug_req__field_descriptors,
  protocol__debug_req__field_indices_by_name,
  1,  protocol__debug_req__number_ranges,
  (ProtobufCMessageInit) protocol__debug_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
