/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Debug.proto */

#ifndef PROTOBUF_C_Debug_2eproto__INCLUDED
#define PROTOBUF_C_Debug_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IdentityMsg.pb-c.h"

typedef struct _Protocol__DebugReq Protocol__DebugReq;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__DebugReq
{
  ProtobufCMessage base;
  Protocol__IdentityMsg *iden;
  char *message;
};
#define PROTOCOL__DEBUG_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__debug_req__descriptor) \
    , NULL, NULL }


/* Protocol__DebugReq methods */
void   protocol__debug_req__init
                     (Protocol__DebugReq         *message);
size_t protocol__debug_req__get_packed_size
                     (const Protocol__DebugReq   *message);
size_t protocol__debug_req__pack
                     (const Protocol__DebugReq   *message,
                      uint8_t             *out);
size_t protocol__debug_req__pack_to_buffer
                     (const Protocol__DebugReq   *message,
                      ProtobufCBuffer     *buffer);
Protocol__DebugReq *
       protocol__debug_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__debug_req__free_unpacked
                     (Protocol__DebugReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__DebugReq_Closure)
                 (const Protocol__DebugReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__debug_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Debug_2eproto__INCLUDED */
