# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Define.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Define.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x44\x65\x66ine.proto\x12\x08protocol*\xa1\x06\n\nHeaderType\x12\x13\n\x0fTypeRegisterReq\x10\x02\x12\x13\n\x0fTypeRegisterRsp\x10\x03\x12\x14\n\x10TypeParameterReq\x10\x04\x12\x14\n\x10TypeParameterRsp\x10\x05\x12\x12\n\x0eTypeSettingReq\x10\x06\x12\x12\n\x0eTypeSettingRsp\x10\x07\x12\x0e\n\nTypeEnvReq\x10\x08\x12\x0e\n\nTypeEnvRsp\x10\t\x12\x13\n\x0fTypeBehaviorReq\x10\n\x12\x13\n\x0fTypeBehaviorRsp\x10\x0b\x12\x0e\n\nTypeGPSReq\x10\x0c\x12\x0e\n\nTypeGPSRsp\x10\r\x12\x13\n\x0fTypeCellularReq\x10\x0e\x12\x13\n\x0fTypeCellularRsp\x10\x0f\x12\x12\n\x0eTypeWarningReq\x10\x10\x12\x12\n\x0eTypewarningRsp\x10\x11\x12\x13\n\x0fTypeDownloadReq\x10\x12\x12\x13\n\x0fTypeDownloadRsp\x10\x13\x12\x11\n\rTypeUploadReq\x10\x14\x12\x11\n\rTypeUploadRsp\x10\x15\x12\x1a\n\x16TypeSettingAndParamReq\x10\x16\x12\x1a\n\x16TypeSettingAndParamRsp\x10\x17\x12\x0e\n\nTypeSMSMsg\x10\x18\x12\x0f\n\x0bTypeSMSRply\x10\x19\x12\x14\n\x10TypeBehavior2Req\x10\x1a\x12\x14\n\x10TypeBehavior2Rsp\x10\x1b\x12\x11\n\rTypeEstrusReq\x10\x1c\x12\x11\n\rTypeEstrusRsp\x10\x1d\x12\x11\n\rTypeOriginReq\x10\x1e\x12\x11\n\rTypeOriginRsp\x10\x1f\x12\x11\n\rTypeStatusReq\x10 \x12\x11\n\rTypeStatusRsp\x10!\x12\x11\n\x0cTypeDebugReq\x10\xea\x07\x12\x11\n\x0cTypeDebugRsp\x10\xeb\x07\x12\x12\n\rTypeSensorReq\x10\xec\x07\x12\x12\n\rTypeSensorRsp\x10\xed\x07\x12\x10\n\x0bTypePingReq\x10\xee\x07\x12\x10\n\x0bTypePingRsp\x10\xef\x07\x12\x0f\n\nTypeAppReq\x10\xf0\x07\x12\x0f\n\nTypeAppRsp\x10\xf1\x07')
)

_HEADERTYPE = _descriptor.EnumDescriptor(
  name='HeaderType',
  full_name='protocol.HeaderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TypeRegisterReq', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeRegisterRsp', index=1, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeParameterReq', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeParameterRsp', index=3, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSettingReq', index=4, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSettingRsp', index=5, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeEnvReq', index=6, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeEnvRsp', index=7, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeBehaviorReq', index=8, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeBehaviorRsp', index=9, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeGPSReq', index=10, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeGPSRsp', index=11, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeCellularReq', index=12, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeCellularRsp', index=13, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeWarningReq', index=14, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypewarningRsp', index=15, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeDownloadReq', index=16, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeDownloadRsp', index=17, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeUploadReq', index=18, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeUploadRsp', index=19, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSettingAndParamReq', index=20, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSettingAndParamRsp', index=21, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSMSMsg', index=22, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSMSRply', index=23, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeBehavior2Req', index=24, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeBehavior2Rsp', index=25, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeEstrusReq', index=26, number=28,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeEstrusRsp', index=27, number=29,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeOriginReq', index=28, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeOriginRsp', index=29, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeStatusReq', index=30, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeStatusRsp', index=31, number=33,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeDebugReq', index=32, number=1002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeDebugRsp', index=33, number=1003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSensorReq', index=34, number=1004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeSensorRsp', index=35, number=1005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypePingReq', index=36, number=1006,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypePingRsp', index=37, number=1007,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeAppReq', index=38, number=1008,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeAppRsp', index=39, number=1009,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=27,
  serialized_end=828,
)
_sym_db.RegisterEnumDescriptor(_HEADERTYPE)

HeaderType = enum_type_wrapper.EnumTypeWrapper(_HEADERTYPE)
TypeRegisterReq = 2
TypeRegisterRsp = 3
TypeParameterReq = 4
TypeParameterRsp = 5
TypeSettingReq = 6
TypeSettingRsp = 7
TypeEnvReq = 8
TypeEnvRsp = 9
TypeBehaviorReq = 10
TypeBehaviorRsp = 11
TypeGPSReq = 12
TypeGPSRsp = 13
TypeCellularReq = 14
TypeCellularRsp = 15
TypeWarningReq = 16
TypewarningRsp = 17
TypeDownloadReq = 18
TypeDownloadRsp = 19
TypeUploadReq = 20
TypeUploadRsp = 21
TypeSettingAndParamReq = 22
TypeSettingAndParamRsp = 23
TypeSMSMsg = 24
TypeSMSRply = 25
TypeBehavior2Req = 26
TypeBehavior2Rsp = 27
TypeEstrusReq = 28
TypeEstrusRsp = 29
TypeOriginReq = 30
TypeOriginRsp = 31
TypeStatusReq = 32
TypeStatusRsp = 33
TypeDebugReq = 1002
TypeDebugRsp = 1003
TypeSensorReq = 1004
TypeSensorRsp = 1005
TypePingReq = 1006
TypePingRsp = 1007
TypeAppReq = 1008
TypeAppRsp = 1009


DESCRIPTOR.enum_types_by_name['HeaderType'] = _HEADERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
