/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Download.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Download.pb-c.h"
void   protocol__download_req__init
                     (Protocol__DownloadReq         *message)
{
  static const Protocol__DownloadReq init_value = PROTOCOL__DOWNLOAD_REQ__INIT;
  *message = init_value;
}
size_t protocol__download_req__get_packed_size
                     (const Protocol__DownloadReq *message)
{
  assert(message->base.descriptor == &protocol__download_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__download_req__pack
                     (const Protocol__DownloadReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__download_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__download_req__pack_to_buffer
                     (const Protocol__DownloadReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__download_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__DownloadReq *
       protocol__download_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__DownloadReq *)
     protobuf_c_message_unpack (&protocol__download_req__descriptor,
                                allocator, len, data);
}
void   protocol__download_req__free_unpacked
                     (Protocol__DownloadReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__download_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__download_rsp__init
                     (Protocol__DownloadRsp         *message)
{
  static const Protocol__DownloadRsp init_value = PROTOCOL__DOWNLOAD_RSP__INIT;
  *message = init_value;
}
size_t protocol__download_rsp__get_packed_size
                     (const Protocol__DownloadRsp *message)
{
  assert(message->base.descriptor == &protocol__download_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__download_rsp__pack
                     (const Protocol__DownloadRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__download_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__download_rsp__pack_to_buffer
                     (const Protocol__DownloadRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__download_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__DownloadRsp *
       protocol__download_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__DownloadRsp *)
     protobuf_c_message_unpack (&protocol__download_rsp__descriptor,
                                allocator, len, data);
}
void   protocol__download_rsp__free_unpacked
                     (Protocol__DownloadRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__download_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char protocol__download_req__file_id__default_value[] = "";
static const int32_t protocol__download_req__begin__default_value = 0;
static const int32_t protocol__download_req__length__default_value = 1400;
static const ProtobufCFieldDescriptor protocol__download_req__field_descriptors[4] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__DownloadReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FileId",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__DownloadReq, fileid),
    NULL,
    &protocol__download_req__file_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Begin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__DownloadReq, has_begin),
    offsetof(Protocol__DownloadReq, begin),
    NULL,
    &protocol__download_req__begin__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Length",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__DownloadReq, has_length),
    offsetof(Protocol__DownloadReq, length),
    NULL,
    &protocol__download_req__length__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__download_req__field_indices_by_name[] = {
  2,   /* field[2] = Begin */
  1,   /* field[1] = FileId */
  0,   /* field[0] = Iden */
  3,   /* field[3] = Length */
};
static const ProtobufCIntRange protocol__download_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protocol__download_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.DownloadReq",
  "DownloadReq",
  "Protocol__DownloadReq",
  "protocol",
  sizeof(Protocol__DownloadReq),
  4,
  protocol__download_req__field_descriptors,
  protocol__download_req__field_indices_by_name,
  1,  protocol__download_req__number_ranges,
  (ProtobufCMessageInit) protocol__download_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
uint8_t protocol__download_rsp__data__default_value_data[] = "";
static const int32_t protocol__download_rsp__total__default_value = 0;
static const int32_t protocol__download_rsp__begin__default_value = 0;
static const int32_t protocol__download_rsp__length__default_value = 0;
static const ProtobufCBinaryData protocol__download_rsp__data__default_value = { 0, protocol__download_rsp__data__default_value_data };
static const ProtobufCFieldDescriptor protocol__download_rsp__field_descriptors[5] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__DownloadRsp, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Total",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__DownloadRsp, has_total),
    offsetof(Protocol__DownloadRsp, total),
    NULL,
    &protocol__download_rsp__total__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Begin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__DownloadRsp, has_begin),
    offsetof(Protocol__DownloadRsp, begin),
    NULL,
    &protocol__download_rsp__begin__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Length",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__DownloadRsp, has_length),
    offsetof(Protocol__DownloadRsp, length),
    NULL,
    &protocol__download_rsp__length__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Data",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Protocol__DownloadRsp, has_data),
    offsetof(Protocol__DownloadRsp, data),
    NULL,
    &protocol__download_rsp__data__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__download_rsp__field_indices_by_name[] = {
  2,   /* field[2] = Begin */
  4,   /* field[4] = Data */
  0,   /* field[0] = Iden */
  3,   /* field[3] = Length */
  1,   /* field[1] = Total */
};
static const ProtobufCIntRange protocol__download_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protocol__download_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.DownloadRsp",
  "DownloadRsp",
  "Protocol__DownloadRsp",
  "protocol",
  sizeof(Protocol__DownloadRsp),
  5,
  protocol__download_rsp__field_descriptors,
  protocol__download_rsp__field_indices_by_name,
  1,  protocol__download_rsp__number_ranges,
  (ProtobufCMessageInit) protocol__download_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
