# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Download.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Download.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x44ownload.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"l\n\x0b\x44ownloadReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x10\n\x06\x46ileId\x18\x02 \x01(\t:\x00\x12\x10\n\x05\x42\x65gin\x18\x03 \x01(\x05:\x01\x30\x12\x14\n\x06Length\x18\x04 \x01(\x05:\x04\x31\x34\x30\x30\"y\n\x0b\x44ownloadRsp\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x10\n\x05Total\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x05\x42\x65gin\x18\x03 \x01(\x05:\x01\x30\x12\x11\n\x06Length\x18\x04 \x01(\x05:\x01\x30\x12\x0e\n\x04\x44\x61ta\x18\x05 \x01(\x0c:\x00')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_DOWNLOADREQ = _descriptor.Descriptor(
  name='DownloadReq',
  full_name='protocol.DownloadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.DownloadReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FileId', full_name='protocol.DownloadReq.FileId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Begin', full_name='protocol.DownloadReq.Begin', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Length', full_name='protocol.DownloadReq.Length', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1400,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=155,
)


_DOWNLOADRSP = _descriptor.Descriptor(
  name='DownloadRsp',
  full_name='protocol.DownloadRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.DownloadRsp.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Total', full_name='protocol.DownloadRsp.Total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Begin', full_name='protocol.DownloadRsp.Begin', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Length', full_name='protocol.DownloadRsp.Length', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='protocol.DownloadRsp.Data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=278,
)

_DOWNLOADREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_DOWNLOADRSP.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
DESCRIPTOR.message_types_by_name['DownloadReq'] = _DOWNLOADREQ
DESCRIPTOR.message_types_by_name['DownloadRsp'] = _DOWNLOADRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DownloadReq = _reflection.GeneratedProtocolMessageType('DownloadReq', (_message.Message,), dict(
  DESCRIPTOR = _DOWNLOADREQ,
  __module__ = 'Download_pb2'
  # @@protoc_insertion_point(class_scope:protocol.DownloadReq)
  ))
_sym_db.RegisterMessage(DownloadReq)

DownloadRsp = _reflection.GeneratedProtocolMessageType('DownloadRsp', (_message.Message,), dict(
  DESCRIPTOR = _DOWNLOADRSP,
  __module__ = 'Download_pb2'
  # @@protoc_insertion_point(class_scope:protocol.DownloadRsp)
  ))
_sym_db.RegisterMessage(DownloadRsp)


# @@protoc_insertion_point(module_scope)
