/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Env.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Env.pb-c.h"
void   protocol__env_req__init
                     (Protocol__EnvReq         *message)
{
  static const Protocol__EnvReq init_value = PROTOCOL__ENV_REQ__INIT;
  *message = init_value;
}
size_t protocol__env_req__get_packed_size
                     (const Protocol__EnvReq *message)
{
  assert(message->base.descriptor == &protocol__env_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__env_req__pack
                     (const Protocol__EnvReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__env_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__env_req__pack_to_buffer
                     (const Protocol__EnvReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__env_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__EnvReq *
       protocol__env_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__EnvReq *)
     protobuf_c_message_unpack (&protocol__env_req__descriptor,
                                allocator, len, data);
}
void   protocol__env_req__free_unpacked
                     (Protocol__EnvReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__env_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__env__init
                     (Protocol__Env         *message)
{
  static const Protocol__Env init_value = PROTOCOL__ENV__INIT;
  *message = init_value;
}
size_t protocol__env__get_packed_size
                     (const Protocol__Env *message)
{
  assert(message->base.descriptor == &protocol__env__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__env__pack
                     (const Protocol__Env *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__env__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__env__pack_to_buffer
                     (const Protocol__Env *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__env__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Env *
       protocol__env__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Env *)
     protobuf_c_message_unpack (&protocol__env__descriptor,
                                allocator, len, data);
}
void   protocol__env__free_unpacked
                     (Protocol__Env *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__env__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__env_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__EnvReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EnvInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__EnvReq, n_envinfo),
    offsetof(Protocol__EnvReq, envinfo),
    &protocol__env__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__env_req__field_indices_by_name[] = {
  1,   /* field[1] = EnvInfo */
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__env_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__env_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.EnvReq",
  "EnvReq",
  "Protocol__EnvReq",
  "protocol",
  sizeof(Protocol__EnvReq),
  2,
  protocol__env_req__field_descriptors,
  protocol__env_req__field_indices_by_name,
  1,  protocol__env_req__number_ranges,
  (ProtobufCMessageInit) protocol__env_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__env__timestamp__default_value = 0u;
static const int32_t protocol__env__battery_power__default_value = 0;
static const int32_t protocol__env__battery_voltage__default_value = 0;
static const int32_t protocol__env__charge_voltage__default_value = 0;
static const int32_t protocol__env__charge_current__default_value = 0;
static const int32_t protocol__env__inner_temperature__default_value = 0;
static const int32_t protocol__env__inner_humidity__default_value = 0;
static const int32_t protocol__env__inner_pressure__default_value = 0;
static const int32_t protocol__env__ambient_light__default_value = 0;
static const ProtobufCFieldDescriptor protocol__env__field_descriptors[9] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Env, has_timestamp),
    offsetof(Protocol__Env, timestamp),
    NULL,
    &protocol__env__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BatteryPower",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_batterypower),
    offsetof(Protocol__Env, batterypower),
    NULL,
    &protocol__env__battery_power__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BatteryVoltage",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_batteryvoltage),
    offsetof(Protocol__Env, batteryvoltage),
    NULL,
    &protocol__env__battery_voltage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ChargeVoltage",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_chargevoltage),
    offsetof(Protocol__Env, chargevoltage),
    NULL,
    &protocol__env__charge_voltage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ChargeCurrent",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_chargecurrent),
    offsetof(Protocol__Env, chargecurrent),
    NULL,
    &protocol__env__charge_current__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "InnerTemperature",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Env, has_innertemperature),
    offsetof(Protocol__Env, innertemperature),
    NULL,
    &protocol__env__inner_temperature__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "InnerHumidity",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_innerhumidity),
    offsetof(Protocol__Env, innerhumidity),
    NULL,
    &protocol__env__inner_humidity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "InnerPressure",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_innerpressure),
    offsetof(Protocol__Env, innerpressure),
    NULL,
    &protocol__env__inner_pressure__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "AmbientLight",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Env, has_ambientlight),
    offsetof(Protocol__Env, ambientlight),
    NULL,
    &protocol__env__ambient_light__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__env__field_indices_by_name[] = {
  8,   /* field[8] = AmbientLight */
  1,   /* field[1] = BatteryPower */
  2,   /* field[2] = BatteryVoltage */
  4,   /* field[4] = ChargeCurrent */
  3,   /* field[3] = ChargeVoltage */
  6,   /* field[6] = InnerHumidity */
  7,   /* field[7] = InnerPressure */
  5,   /* field[5] = InnerTemperature */
  0,   /* field[0] = Timestamp */
};
static const ProtobufCIntRange protocol__env__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor protocol__env__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Env",
  "Env",
  "Protocol__Env",
  "protocol",
  sizeof(Protocol__Env),
  9,
  protocol__env__field_descriptors,
  protocol__env__field_indices_by_name,
  1,  protocol__env__number_ranges,
  (ProtobufCMessageInit) protocol__env__init,
  NULL,NULL,NULL    /* reserved[123] */
};
