# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Env.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Env.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\tEnv.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"M\n\x06\x45nvReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x1e\n\x07\x45nvInfo\x18\x02 \x03(\x0b\x32\r.protocol.Env\"\xed\x01\n\x03\x45nv\x12\x14\n\tTimestamp\x18\x01 \x01(\r:\x01\x30\x12\x17\n\x0c\x42\x61tteryPower\x18\x02 \x01(\x05:\x01\x30\x12\x19\n\x0e\x42\x61tteryVoltage\x18\x03 \x01(\x05:\x01\x30\x12\x18\n\rChargeVoltage\x18\x04 \x01(\x05:\x01\x30\x12\x18\n\rChargeCurrent\x18\x05 \x01(\x05:\x01\x30\x12\x1b\n\x10InnerTemperature\x18\x06 \x01(\x11:\x01\x30\x12\x18\n\rInnerHumidity\x18\x07 \x01(\x05:\x01\x30\x12\x18\n\rInnerPressure\x18\x08 \x01(\x05:\x01\x30\x12\x17\n\x0c\x41mbientLight\x18\t \x01(\x05:\x01\x30')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_ENVREQ = _descriptor.Descriptor(
  name='EnvReq',
  full_name='protocol.EnvReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.EnvReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EnvInfo', full_name='protocol.EnvReq.EnvInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=119,
)


_ENV = _descriptor.Descriptor(
  name='Env',
  full_name='protocol.Env',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.Env.Timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatteryPower', full_name='protocol.Env.BatteryPower', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatteryVoltage', full_name='protocol.Env.BatteryVoltage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChargeVoltage', full_name='protocol.Env.ChargeVoltage', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChargeCurrent', full_name='protocol.Env.ChargeCurrent', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InnerTemperature', full_name='protocol.Env.InnerTemperature', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InnerHumidity', full_name='protocol.Env.InnerHumidity', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InnerPressure', full_name='protocol.Env.InnerPressure', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AmbientLight', full_name='protocol.Env.AmbientLight', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=359,
)

_ENVREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_ENVREQ.fields_by_name['EnvInfo'].message_type = _ENV
DESCRIPTOR.message_types_by_name['EnvReq'] = _ENVREQ
DESCRIPTOR.message_types_by_name['Env'] = _ENV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvReq = _reflection.GeneratedProtocolMessageType('EnvReq', (_message.Message,), dict(
  DESCRIPTOR = _ENVREQ,
  __module__ = 'Env_pb2'
  # @@protoc_insertion_point(class_scope:protocol.EnvReq)
  ))
_sym_db.RegisterMessage(EnvReq)

Env = _reflection.GeneratedProtocolMessageType('Env', (_message.Message,), dict(
  DESCRIPTOR = _ENV,
  __module__ = 'Env_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Env)
  ))
_sym_db.RegisterMessage(Env)


# @@protoc_insertion_point(module_scope)
