/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Estrus.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Estrus.pb-c.h"
void   protocol__estrus_req__init
                     (Protocol__EstrusReq         *message)
{
  static const Protocol__EstrusReq init_value = PROTOCOL__ESTRUS_REQ__INIT;
  *message = init_value;
}
size_t protocol__estrus_req__get_packed_size
                     (const Protocol__EstrusReq *message)
{
  assert(message->base.descriptor == &protocol__estrus_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__estrus_req__pack
                     (const Protocol__EstrusReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__estrus_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__estrus_req__pack_to_buffer
                     (const Protocol__EstrusReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__estrus_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__EstrusReq *
       protocol__estrus_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__EstrusReq *)
     protobuf_c_message_unpack (&protocol__estrus_req__descriptor,
                                allocator, len, data);
}
void   protocol__estrus_req__free_unpacked
                     (Protocol__EstrusReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__estrus_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__estrus__init
                     (Protocol__Estrus         *message)
{
  static const Protocol__Estrus init_value = PROTOCOL__ESTRUS__INIT;
  *message = init_value;
}
size_t protocol__estrus__get_packed_size
                     (const Protocol__Estrus *message)
{
  assert(message->base.descriptor == &protocol__estrus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__estrus__pack
                     (const Protocol__Estrus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__estrus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__estrus__pack_to_buffer
                     (const Protocol__Estrus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__estrus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Estrus *
       protocol__estrus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Estrus *)
     protobuf_c_message_unpack (&protocol__estrus__descriptor,
                                allocator, len, data);
}
void   protocol__estrus__free_unpacked
                     (Protocol__Estrus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__estrus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__estrus_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__EstrusReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EstrusInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__EstrusReq, n_estrusinfo),
    offsetof(Protocol__EstrusReq, estrusinfo),
    &protocol__estrus__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__estrus_req__field_indices_by_name[] = {
  1,   /* field[1] = EstrusInfo */
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__estrus_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__estrus_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.EstrusReq",
  "EstrusReq",
  "Protocol__EstrusReq",
  "protocol",
  sizeof(Protocol__EstrusReq),
  2,
  protocol__estrus_req__field_descriptors,
  protocol__estrus_req__field_indices_by_name,
  1,  protocol__estrus_req__number_ranges,
  (ProtobufCMessageInit) protocol__estrus_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__estrus__timestamp__default_value = 0u;
static const int32_t protocol__estrus__activity__default_value = 0;
static const int32_t protocol__estrus__odba__default_value = 0;
static const ProtobufCFieldDescriptor protocol__estrus__field_descriptors[3] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Estrus, has_timestamp),
    offsetof(Protocol__Estrus, timestamp),
    NULL,
    &protocol__estrus__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Activity",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Estrus, has_activity),
    offsetof(Protocol__Estrus, activity),
    NULL,
    &protocol__estrus__activity__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ODBA",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Estrus, has_odba),
    offsetof(Protocol__Estrus, odba),
    NULL,
    &protocol__estrus__odba__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__estrus__field_indices_by_name[] = {
  1,   /* field[1] = Activity */
  2,   /* field[2] = ODBA */
  0,   /* field[0] = Timestamp */
};
static const ProtobufCIntRange protocol__estrus__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__estrus__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Estrus",
  "Estrus",
  "Protocol__Estrus",
  "protocol",
  sizeof(Protocol__Estrus),
  3,
  protocol__estrus__field_descriptors,
  protocol__estrus__field_indices_by_name,
  1,  protocol__estrus__number_ranges,
  (ProtobufCMessageInit) protocol__estrus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
