# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Estrus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Estrus.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x45strus.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"V\n\tEstrusReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12$\n\nEstrusInfo\x18\x02 \x03(\x0b\x32\x10.protocol.Estrus\"D\n\x06\x45strus\x12\x14\n\tTimestamp\x18\x01 \x01(\r:\x01\x30\x12\x13\n\x08\x41\x63tivity\x18\x02 \x01(\x05:\x01\x30\x12\x0f\n\x04ODBA\x18\x03 \x01(\x05:\x01\x30')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_ESTRUSREQ = _descriptor.Descriptor(
  name='EstrusReq',
  full_name='protocol.EstrusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.EstrusReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstrusInfo', full_name='protocol.EstrusReq.EstrusInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=131,
)


_ESTRUS = _descriptor.Descriptor(
  name='Estrus',
  full_name='protocol.Estrus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.Estrus.Timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Activity', full_name='protocol.Estrus.Activity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ODBA', full_name='protocol.Estrus.ODBA', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=201,
)

_ESTRUSREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_ESTRUSREQ.fields_by_name['EstrusInfo'].message_type = _ESTRUS
DESCRIPTOR.message_types_by_name['EstrusReq'] = _ESTRUSREQ
DESCRIPTOR.message_types_by_name['Estrus'] = _ESTRUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstrusReq = _reflection.GeneratedProtocolMessageType('EstrusReq', (_message.Message,), dict(
  DESCRIPTOR = _ESTRUSREQ,
  __module__ = 'Estrus_pb2'
  # @@protoc_insertion_point(class_scope:protocol.EstrusReq)
  ))
_sym_db.RegisterMessage(EstrusReq)

Estrus = _reflection.GeneratedProtocolMessageType('Estrus', (_message.Message,), dict(
  DESCRIPTOR = _ESTRUS,
  __module__ = 'Estrus_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Estrus)
  ))
_sym_db.RegisterMessage(Estrus)


# @@protoc_insertion_point(module_scope)
