/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: GPS.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "GPS.pb-c.h"
void   protocol__gpsreq__init
                     (Protocol__GPSReq         *message)
{
  static const Protocol__GPSReq init_value = PROTOCOL__GPSREQ__INIT;
  *message = init_value;
}
size_t protocol__gpsreq__get_packed_size
                     (const Protocol__GPSReq *message)
{
  assert(message->base.descriptor == &protocol__gpsreq__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__gpsreq__pack
                     (const Protocol__GPSReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__gpsreq__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__gpsreq__pack_to_buffer
                     (const Protocol__GPSReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__gpsreq__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__GPSReq *
       protocol__gpsreq__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__GPSReq *)
     protobuf_c_message_unpack (&protocol__gpsreq__descriptor,
                                allocator, len, data);
}
void   protocol__gpsreq__free_unpacked
                     (Protocol__GPSReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__gpsreq__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__satellite__init
                     (Protocol__Satellite         *message)
{
  static const Protocol__Satellite init_value = PROTOCOL__SATELLITE__INIT;
  *message = init_value;
}
size_t protocol__satellite__get_packed_size
                     (const Protocol__Satellite *message)
{
  assert(message->base.descriptor == &protocol__satellite__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__satellite__pack
                     (const Protocol__Satellite *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__satellite__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__satellite__pack_to_buffer
                     (const Protocol__Satellite *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__satellite__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Satellite *
       protocol__satellite__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Satellite *)
     protobuf_c_message_unpack (&protocol__satellite__descriptor,
                                allocator, len, data);
}
void   protocol__satellite__free_unpacked
                     (Protocol__Satellite *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__satellite__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__gps__init
                     (Protocol__GPS         *message)
{
  static const Protocol__GPS init_value = PROTOCOL__GPS__INIT;
  *message = init_value;
}
size_t protocol__gps__get_packed_size
                     (const Protocol__GPS *message)
{
  assert(message->base.descriptor == &protocol__gps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__gps__pack
                     (const Protocol__GPS *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__gps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__gps__pack_to_buffer
                     (const Protocol__GPS *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__gps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__GPS *
       protocol__gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__GPS *)
     protobuf_c_message_unpack (&protocol__gps__descriptor,
                                allocator, len, data);
}
void   protocol__gps__free_unpacked
                     (Protocol__GPS *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__gps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__gpsreq__field_descriptors[3] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__GPSReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__GPSReq, n_gpsinfo),
    offsetof(Protocol__GPSReq, gpsinfo),
    &protocol__gps__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SMS",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPSReq, has_sms),
    offsetof(Protocol__GPSReq, sms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__gpsreq__field_indices_by_name[] = {
  1,   /* field[1] = GPSInfo */
  0,   /* field[0] = Iden */
  2,   /* field[2] = SMS */
};
static const ProtobufCIntRange protocol__gpsreq__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__gpsreq__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.GPSReq",
  "GPSReq",
  "Protocol__GPSReq",
  "protocol",
  sizeof(Protocol__GPSReq),
  3,
  protocol__gpsreq__field_descriptors,
  protocol__gpsreq__field_indices_by_name,
  1,  protocol__gpsreq__number_ranges,
  (ProtobufCMessageInit) protocol__gpsreq__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char protocol__satellite__type__default_value[] = "";
static const int32_t protocol__satellite__elevation__default_value = -1;
static const int32_t protocol__satellite__azimuth__default_value = -1;
static const int32_t protocol__satellite__snr__default_value = -1;
static const int32_t protocol__satellite__used__default_value = 0;
static const ProtobufCFieldDescriptor protocol__satellite__field_descriptors[6] =
{
  {
    "Id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Satellite, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Elevation",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Satellite, has_elevation),
    offsetof(Protocol__Satellite, elevation),
    NULL,
    &protocol__satellite__elevation__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Azimuth",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Satellite, has_azimuth),
    offsetof(Protocol__Satellite, azimuth),
    NULL,
    &protocol__satellite__azimuth__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SNR",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__Satellite, has_snr),
    offsetof(Protocol__Satellite, snr),
    NULL,
    &protocol__satellite__snr__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Used",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Satellite, has_used),
    offsetof(Protocol__Satellite, used),
    NULL,
    &protocol__satellite__used__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__Satellite, type),
    NULL,
    &protocol__satellite__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__satellite__field_indices_by_name[] = {
  2,   /* field[2] = Azimuth */
  1,   /* field[1] = Elevation */
  0,   /* field[0] = Id */
  3,   /* field[3] = SNR */
  5,   /* field[5] = Type */
  4,   /* field[4] = Used */
};
static const ProtobufCIntRange protocol__satellite__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor protocol__satellite__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Satellite",
  "Satellite",
  "Protocol__Satellite",
  "protocol",
  sizeof(Protocol__Satellite),
  6,
  protocol__satellite__field_descriptors,
  protocol__satellite__field_indices_by_name,
  1,  protocol__satellite__number_ranges,
  (ProtobufCMessageInit) protocol__satellite__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__gps__timestamp__default_value = 0u;
static const int32_t protocol__gps__latitude__default_value = 2000000000;
static const int32_t protocol__gps__longitude__default_value = 2000000000;
static const int32_t protocol__gps__altitude__default_value = 0;
static const int32_t protocol__gps__quality__default_value = 0;
static const int32_t protocol__gps__mode__default_value = 0;
static const int32_t protocol__gps__pdop__default_value = 0;
static const int32_t protocol__gps__hdop__default_value = 0;
static const int32_t protocol__gps__vdop__default_value = 0;
static const int32_t protocol__gps__satellites_used__default_value = 0;
static const int32_t protocol__gps__satellites_in_view__default_value = 0;
static const int32_t protocol__gps__speed__default_value = 0;
static const int32_t protocol__gps__course__default_value = 0;
static const int32_t protocol__gps__hacc__default_value = 0;
static const int32_t protocol__gps__vacc__default_value = 0;
static const int32_t protocol__gps__fix_time__default_value = 0;
static const ProtobufCFieldDescriptor protocol__gps__field_descriptors[17] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__GPS, has_timestamp),
    offsetof(Protocol__GPS, timestamp),
    NULL,
    &protocol__gps__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Latitude",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__GPS, has_latitude),
    offsetof(Protocol__GPS, latitude),
    NULL,
    &protocol__gps__latitude__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Longitude",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__GPS, has_longitude),
    offsetof(Protocol__GPS, longitude),
    NULL,
    &protocol__gps__longitude__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Altitude",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__GPS, has_altitude),
    offsetof(Protocol__GPS, altitude),
    NULL,
    &protocol__gps__altitude__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Quality",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_quality),
    offsetof(Protocol__GPS, quality),
    NULL,
    &protocol__gps__quality__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Mode",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_mode),
    offsetof(Protocol__GPS, mode),
    NULL,
    &protocol__gps__mode__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PDOP",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_pdop),
    offsetof(Protocol__GPS, pdop),
    NULL,
    &protocol__gps__pdop__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HDOP",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_hdop),
    offsetof(Protocol__GPS, hdop),
    NULL,
    &protocol__gps__hdop__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "VDOP",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_vdop),
    offsetof(Protocol__GPS, vdop),
    NULL,
    &protocol__gps__vdop__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SatellitesUsed",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_satellitesused),
    offsetof(Protocol__GPS, satellitesused),
    NULL,
    &protocol__gps__satellites_used__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SatellitesInView",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_satellitesinview),
    offsetof(Protocol__GPS, satellitesinview),
    NULL,
    &protocol__gps__satellites_in_view__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Speed",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_speed),
    offsetof(Protocol__GPS, speed),
    NULL,
    &protocol__gps__speed__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Course",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Protocol__GPS, has_course),
    offsetof(Protocol__GPS, course),
    NULL,
    &protocol__gps__course__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HACC",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_hacc),
    offsetof(Protocol__GPS, hacc),
    NULL,
    &protocol__gps__hacc__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "VACC",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_vacc),
    offsetof(Protocol__GPS, vacc),
    NULL,
    &protocol__gps__vacc__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FixTime",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__GPS, has_fixtime),
    offsetof(Protocol__GPS, fixtime),
    NULL,
    &protocol__gps__fix_time__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Satellites",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__GPS, n_satellites),
    offsetof(Protocol__GPS, satellites),
    &protocol__satellite__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__gps__field_indices_by_name[] = {
  3,   /* field[3] = Altitude */
  12,   /* field[12] = Course */
  15,   /* field[15] = FixTime */
  13,   /* field[13] = HACC */
  7,   /* field[7] = HDOP */
  1,   /* field[1] = Latitude */
  2,   /* field[2] = Longitude */
  5,   /* field[5] = Mode */
  6,   /* field[6] = PDOP */
  4,   /* field[4] = Quality */
  16,   /* field[16] = Satellites */
  10,   /* field[10] = SatellitesInView */
  9,   /* field[9] = SatellitesUsed */
  11,   /* field[11] = Speed */
  0,   /* field[0] = Timestamp */
  14,   /* field[14] = VACC */
  8,   /* field[8] = VDOP */
};
static const ProtobufCIntRange protocol__gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor protocol__gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.GPS",
  "GPS",
  "Protocol__GPS",
  "protocol",
  sizeof(Protocol__GPS),
  17,
  protocol__gps__field_descriptors,
  protocol__gps__field_indices_by_name,
  1,  protocol__gps__number_ranges,
  (ProtobufCMessageInit) protocol__gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
