# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GPS.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\tGPS.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"Z\n\x06GPSReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x1e\n\x07GPSInfo\x18\x02 \x03(\x0b\x32\r.protocol.GPS\x12\x0b\n\x03SMS\x18\x03 \x01(\x05\"u\n\tSatellite\x12\n\n\x02Id\x18\x01 \x02(\x05\x12\x15\n\tElevation\x18\x02 \x01(\x11:\x02-1\x12\x13\n\x07\x41zimuth\x18\x03 \x01(\x11:\x02-1\x12\x0f\n\x03SNR\x18\x04 \x01(\x11:\x02-1\x12\x0f\n\x04Used\x18\x05 \x01(\x05:\x01\x30\x12\x0e\n\x04Type\x18\x06 \x01(\t:\x00\"\x81\x03\n\x03GPS\x12\x14\n\tTimestamp\x18\x01 \x01(\r:\x01\x30\x12\x1c\n\x08Latitude\x18\x02 \x01(\x11:\n2000000000\x12\x1d\n\tLongitude\x18\x03 \x01(\x11:\n2000000000\x12\x13\n\x08\x41ltitude\x18\x04 \x01(\x11:\x01\x30\x12\x12\n\x07Quality\x18\x05 \x01(\x05:\x01\x30\x12\x0f\n\x04Mode\x18\x06 \x01(\x05:\x01\x30\x12\x0f\n\x04PDOP\x18\x07 \x01(\x05:\x01\x30\x12\x0f\n\x04HDOP\x18\x08 \x01(\x05:\x01\x30\x12\x0f\n\x04VDOP\x18\t \x01(\x05:\x01\x30\x12\x19\n\x0eSatellitesUsed\x18\n \x01(\x05:\x01\x30\x12\x1b\n\x10SatellitesInView\x18\x0b \x01(\x05:\x01\x30\x12\x10\n\x05Speed\x18\x0c \x01(\x05:\x01\x30\x12\x11\n\x06\x43ourse\x18\r \x01(\x11:\x01\x30\x12\x0f\n\x04HACC\x18\x0e \x01(\x05:\x01\x30\x12\x0f\n\x04VACC\x18\x0f \x01(\x05:\x01\x30\x12\x12\n\x07\x46ixTime\x18\x10 \x01(\x05:\x01\x30\x12\'\n\nSatellites\x18\x11 \x03(\x0b\x32\x13.protocol.Satellite')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_GPSREQ = _descriptor.Descriptor(
  name='GPSReq',
  full_name='protocol.GPSReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.GPSReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSInfo', full_name='protocol.GPSReq.GPSInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMS', full_name='protocol.GPSReq.SMS', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=132,
)


_SATELLITE = _descriptor.Descriptor(
  name='Satellite',
  full_name='protocol.Satellite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='protocol.Satellite.Id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Elevation', full_name='protocol.Satellite.Elevation', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Azimuth', full_name='protocol.Satellite.Azimuth', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SNR', full_name='protocol.Satellite.SNR', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Used', full_name='protocol.Satellite.Used', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Type', full_name='protocol.Satellite.Type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=251,
)


_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='protocol.GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.GPS.Timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='protocol.GPS.Latitude', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=2000000000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='protocol.GPS.Longitude', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=2000000000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Altitude', full_name='protocol.GPS.Altitude', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Quality', full_name='protocol.GPS.Quality', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Mode', full_name='protocol.GPS.Mode', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PDOP', full_name='protocol.GPS.PDOP', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HDOP', full_name='protocol.GPS.HDOP', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VDOP', full_name='protocol.GPS.VDOP', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SatellitesUsed', full_name='protocol.GPS.SatellitesUsed', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SatellitesInView', full_name='protocol.GPS.SatellitesInView', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Speed', full_name='protocol.GPS.Speed', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Course', full_name='protocol.GPS.Course', index=12,
      number=13, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HACC', full_name='protocol.GPS.HACC', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VACC', full_name='protocol.GPS.VACC', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FixTime', full_name='protocol.GPS.FixTime', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Satellites', full_name='protocol.GPS.Satellites', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=639,
)

_GPSREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_GPSREQ.fields_by_name['GPSInfo'].message_type = _GPS
_GPS.fields_by_name['Satellites'].message_type = _SATELLITE
DESCRIPTOR.message_types_by_name['GPSReq'] = _GPSREQ
DESCRIPTOR.message_types_by_name['Satellite'] = _SATELLITE
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPSReq = _reflection.GeneratedProtocolMessageType('GPSReq', (_message.Message,), dict(
  DESCRIPTOR = _GPSREQ,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:protocol.GPSReq)
  ))
_sym_db.RegisterMessage(GPSReq)

Satellite = _reflection.GeneratedProtocolMessageType('Satellite', (_message.Message,), dict(
  DESCRIPTOR = _SATELLITE,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Satellite)
  ))
_sym_db.RegisterMessage(Satellite)

GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), dict(
  DESCRIPTOR = _GPS,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:protocol.GPS)
  ))
_sym_db.RegisterMessage(GPS)


# @@protoc_insertion_point(module_scope)
