# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IdentityMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IdentityMsg.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x11IdentityMsg.proto\x12\x08protocol\"Y\n\x0bIdentityMsg\x12\x10\n\x08MsgToken\x18\x03 \x02(\r\x12\x10\n\x08MsgIndex\x18\x04 \x02(\r\x12\x12\n\x08\x44\x65viceID\x18\x05 \x01(\t:\x00\x12\x12\n\x07RspCode\x18\x06 \x01(\r:\x01\x30')
)




_IDENTITYMSG = _descriptor.Descriptor(
  name='IdentityMsg',
  full_name='protocol.IdentityMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgToken', full_name='protocol.IdentityMsg.MsgToken', index=0,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MsgIndex', full_name='protocol.IdentityMsg.MsgIndex', index=1,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DeviceID', full_name='protocol.IdentityMsg.DeviceID', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RspCode', full_name='protocol.IdentityMsg.RspCode', index=3,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['IdentityMsg'] = _IDENTITYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentityMsg = _reflection.GeneratedProtocolMessageType('IdentityMsg', (_message.Message,), dict(
  DESCRIPTOR = _IDENTITYMSG,
  __module__ = 'IdentityMsg_pb2'
  # @@protoc_insertion_point(class_scope:protocol.IdentityMsg)
  ))
_sym_db.RegisterMessage(IdentityMsg)


# @@protoc_insertion_point(module_scope)
