/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: IdentityMsg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "IdentityMsg.pb-c.h"
void   protocol__identity_msg__init
                     (Protocol__IdentityMsg         *message)
{
  static const Protocol__IdentityMsg init_value = PROTOCOL__IDENTITY_MSG__INIT;
  *message = init_value;
}
size_t protocol__identity_msg__get_packed_size
                     (const Protocol__IdentityMsg *message)
{
  assert(message->base.descriptor == &protocol__identity_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__identity_msg__pack
                     (const Protocol__IdentityMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__identity_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__identity_msg__pack_to_buffer
                     (const Protocol__IdentityMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__identity_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__IdentityMsg *
       protocol__identity_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__IdentityMsg *)
     protobuf_c_message_unpack (&protocol__identity_msg__descriptor,
                                allocator, len, data);
}
void   protocol__identity_msg__free_unpacked
                     (Protocol__IdentityMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__identity_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char protocol__identity_msg__device_id__default_value[] = "";
static const uint32_t protocol__identity_msg__rsp_code__default_value = 0u;
static const ProtobufCFieldDescriptor protocol__identity_msg__field_descriptors[4] =
{
  {
    "MsgToken",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__IdentityMsg, msgtoken),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MsgIndex",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__IdentityMsg, msgindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DeviceID",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__IdentityMsg, deviceid),
    NULL,
    &protocol__identity_msg__device_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RspCode",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__IdentityMsg, has_rspcode),
    offsetof(Protocol__IdentityMsg, rspcode),
    NULL,
    &protocol__identity_msg__rsp_code__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__identity_msg__field_indices_by_name[] = {
  2,   /* field[2] = DeviceID */
  1,   /* field[1] = MsgIndex */
  0,   /* field[0] = MsgToken */
  3,   /* field[3] = RspCode */
};
static const ProtobufCIntRange protocol__identity_msg__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protocol__identity_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.IdentityMsg",
  "IdentityMsg",
  "Protocol__IdentityMsg",
  "protocol",
  sizeof(Protocol__IdentityMsg),
  4,
  protocol__identity_msg__field_descriptors,
  protocol__identity_msg__field_indices_by_name,
  1,  protocol__identity_msg__number_ranges,
  (ProtobufCMessageInit) protocol__identity_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
