/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Origin.proto */

#ifndef PROTOBUF_C_Origin_2eproto__INCLUDED
#define PROTOBUF_C_Origin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IdentityMsg.pb-c.h"

typedef struct _Protocol__OriginReq Protocol__OriginReq;
typedef struct _Protocol__XYZ Protocol__XYZ;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__OriginReq
{
  ProtobufCMessage base;
  Protocol__IdentityMsg *iden;
  /*
   * 开始时间
   */
  uint32_t timestamp;
  /*
   * 采样频率，每秒次数
   */
  protobuf_c_boolean has_samplingfreq;
  uint32_t samplingfreq;
  size_t n_xyzinfo;
  Protocol__XYZ **xyzinfo;
};
#define PROTOCOL__ORIGIN_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__origin_req__descriptor) \
    , NULL, 0, 0, 0u, 0,NULL }


struct  _Protocol__XYZ
{
  ProtobufCMessage base;
  protobuf_c_boolean has_x;
  int32_t x;
  protobuf_c_boolean has_y;
  int32_t y;
  protobuf_c_boolean has_z;
  int32_t z;
};
#define PROTOCOL__XYZ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__xyz__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* Protocol__OriginReq methods */
void   protocol__origin_req__init
                     (Protocol__OriginReq         *message);
size_t protocol__origin_req__get_packed_size
                     (const Protocol__OriginReq   *message);
size_t protocol__origin_req__pack
                     (const Protocol__OriginReq   *message,
                      uint8_t             *out);
size_t protocol__origin_req__pack_to_buffer
                     (const Protocol__OriginReq   *message,
                      ProtobufCBuffer     *buffer);
Protocol__OriginReq *
       protocol__origin_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__origin_req__free_unpacked
                     (Protocol__OriginReq *message,
                      ProtobufCAllocator *allocator);
/* Protocol__XYZ methods */
void   protocol__xyz__init
                     (Protocol__XYZ         *message);
size_t protocol__xyz__get_packed_size
                     (const Protocol__XYZ   *message);
size_t protocol__xyz__pack
                     (const Protocol__XYZ   *message,
                      uint8_t             *out);
size_t protocol__xyz__pack_to_buffer
                     (const Protocol__XYZ   *message,
                      ProtobufCBuffer     *buffer);
Protocol__XYZ *
       protocol__xyz__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__xyz__free_unpacked
                     (Protocol__XYZ *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__OriginReq_Closure)
                 (const Protocol__OriginReq *message,
                  void *closure_data);
typedef void (*Protocol__XYZ_Closure)
                 (const Protocol__XYZ *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__origin_req__descriptor;
extern const ProtobufCMessageDescriptor protocol__xyz__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Origin_2eproto__INCLUDED */
