# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Origin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Origin.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0cOrigin.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"|\n\tOriginReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x11\n\tTimestamp\x18\x02 \x02(\r\x12\x17\n\x0cSamplingFreq\x18\x03 \x01(\r:\x01\x30\x12\x1e\n\x07XYZInfo\x18\x04 \x03(\x0b\x32\r.protocol.XYZ\"&\n\x03XYZ\x12\t\n\x01X\x18\x01 \x01(\x11\x12\t\n\x01Y\x18\x02 \x01(\x11\x12\t\n\x01Z\x18\x03 \x01(\x11')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_ORIGINREQ = _descriptor.Descriptor(
  name='OriginReq',
  full_name='protocol.OriginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.OriginReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.OriginReq.Timestamp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SamplingFreq', full_name='protocol.OriginReq.SamplingFreq', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='XYZInfo', full_name='protocol.OriginReq.XYZInfo', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=169,
)


_XYZ = _descriptor.Descriptor(
  name='XYZ',
  full_name='protocol.XYZ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='protocol.XYZ.X', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Y', full_name='protocol.XYZ.Y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Z', full_name='protocol.XYZ.Z', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=209,
)

_ORIGINREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_ORIGINREQ.fields_by_name['XYZInfo'].message_type = _XYZ
DESCRIPTOR.message_types_by_name['OriginReq'] = _ORIGINREQ
DESCRIPTOR.message_types_by_name['XYZ'] = _XYZ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OriginReq = _reflection.GeneratedProtocolMessageType('OriginReq', (_message.Message,), dict(
  DESCRIPTOR = _ORIGINREQ,
  __module__ = 'Origin_pb2'
  # @@protoc_insertion_point(class_scope:protocol.OriginReq)
  ))
_sym_db.RegisterMessage(OriginReq)

XYZ = _reflection.GeneratedProtocolMessageType('XYZ', (_message.Message,), dict(
  DESCRIPTOR = _XYZ,
  __module__ = 'Origin_pb2'
  # @@protoc_insertion_point(class_scope:protocol.XYZ)
  ))
_sym_db.RegisterMessage(XYZ)


# @@protoc_insertion_point(module_scope)
