# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Parameter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Parameter.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0fParameter.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"3\n\x0cParameterReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\"\xb3\x02\n\tParameter\x12\x12\n\nServerHost\x18\x01 \x03(\t\x12\x12\n\nServerPort\x18\x02 \x03(\x05\x12\x1c\n\x14SMSAlarmReceiverList\x18\x03 \x03(\t\x12\x1a\n\x12SMSWakeupWhiteList\x18\x04 \x03(\t\x12\x1d\n\x12\x45nvSampleThreshold\x18\x05 \x01(\x05:\x01\x30\x12\"\n\x17\x42\x65haviorSampleThreshold\x18\x06 \x01(\x05:\x01\x30\x12\x1d\n\x12GPSSampleThreshold\x18\x07 \x01(\x05:\x01\x30\x12!\n\x16\x43ommunicationThreshold\x18\x08 \x01(\x05:\x01\x30\x12 \n\x15\x45strusSampleThreshold\x18\x0b \x01(\x05:\x01\x30\x12\x1d\n\x12\x45strusParameterOne\x18\x0c \x01(\x05:\x01\x30\"_\n\x0cParameterRsp\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12*\n\rParameterInfo\x18\x02 \x01(\x0b\x32\x13.protocol.Parameter')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_PARAMETERREQ = _descriptor.Descriptor(
  name='ParameterReq',
  full_name='protocol.ParameterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.ParameterReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=99,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='protocol.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ServerHost', full_name='protocol.Parameter.ServerHost', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ServerPort', full_name='protocol.Parameter.ServerPort', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMSAlarmReceiverList', full_name='protocol.Parameter.SMSAlarmReceiverList', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMSWakeupWhiteList', full_name='protocol.Parameter.SMSWakeupWhiteList', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EnvSampleThreshold', full_name='protocol.Parameter.EnvSampleThreshold', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BehaviorSampleThreshold', full_name='protocol.Parameter.BehaviorSampleThreshold', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSSampleThreshold', full_name='protocol.Parameter.GPSSampleThreshold', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CommunicationThreshold', full_name='protocol.Parameter.CommunicationThreshold', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstrusSampleThreshold', full_name='protocol.Parameter.EstrusSampleThreshold', index=8,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstrusParameterOne', full_name='protocol.Parameter.EstrusParameterOne', index=9,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=409,
)


_PARAMETERRSP = _descriptor.Descriptor(
  name='ParameterRsp',
  full_name='protocol.ParameterRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.ParameterRsp.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ParameterInfo', full_name='protocol.ParameterRsp.ParameterInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=506,
)

_PARAMETERREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_PARAMETERRSP.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_PARAMETERRSP.fields_by_name['ParameterInfo'].message_type = _PARAMETER
DESCRIPTOR.message_types_by_name['ParameterReq'] = _PARAMETERREQ
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['ParameterRsp'] = _PARAMETERRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParameterReq = _reflection.GeneratedProtocolMessageType('ParameterReq', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERREQ,
  __module__ = 'Parameter_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ParameterReq)
  ))
_sym_db.RegisterMessage(ParameterReq)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'Parameter_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

ParameterRsp = _reflection.GeneratedProtocolMessageType('ParameterRsp', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERRSP,
  __module__ = 'Parameter_pb2'
  # @@protoc_insertion_point(class_scope:protocol.ParameterRsp)
  ))
_sym_db.RegisterMessage(ParameterRsp)


# @@protoc_insertion_point(module_scope)
