/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Parameter.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Parameter.pb-c.h"
void   protocol__parameter_req__init
                     (Protocol__ParameterReq         *message)
{
  static const Protocol__ParameterReq init_value = PROTOCOL__PARAMETER_REQ__INIT;
  *message = init_value;
}
size_t protocol__parameter_req__get_packed_size
                     (const Protocol__ParameterReq *message)
{
  assert(message->base.descriptor == &protocol__parameter_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__parameter_req__pack
                     (const Protocol__ParameterReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__parameter_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__parameter_req__pack_to_buffer
                     (const Protocol__ParameterReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__parameter_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__ParameterReq *
       protocol__parameter_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__ParameterReq *)
     protobuf_c_message_unpack (&protocol__parameter_req__descriptor,
                                allocator, len, data);
}
void   protocol__parameter_req__free_unpacked
                     (Protocol__ParameterReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__parameter_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__parameter__init
                     (Protocol__Parameter         *message)
{
  static const Protocol__Parameter init_value = PROTOCOL__PARAMETER__INIT;
  *message = init_value;
}
size_t protocol__parameter__get_packed_size
                     (const Protocol__Parameter *message)
{
  assert(message->base.descriptor == &protocol__parameter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__parameter__pack
                     (const Protocol__Parameter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__parameter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__parameter__pack_to_buffer
                     (const Protocol__Parameter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__parameter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Parameter *
       protocol__parameter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Parameter *)
     protobuf_c_message_unpack (&protocol__parameter__descriptor,
                                allocator, len, data);
}
void   protocol__parameter__free_unpacked
                     (Protocol__Parameter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__parameter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__parameter_rsp__init
                     (Protocol__ParameterRsp         *message)
{
  static const Protocol__ParameterRsp init_value = PROTOCOL__PARAMETER_RSP__INIT;
  *message = init_value;
}
size_t protocol__parameter_rsp__get_packed_size
                     (const Protocol__ParameterRsp *message)
{
  assert(message->base.descriptor == &protocol__parameter_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__parameter_rsp__pack
                     (const Protocol__ParameterRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__parameter_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__parameter_rsp__pack_to_buffer
                     (const Protocol__ParameterRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__parameter_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__ParameterRsp *
       protocol__parameter_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__ParameterRsp *)
     protobuf_c_message_unpack (&protocol__parameter_rsp__descriptor,
                                allocator, len, data);
}
void   protocol__parameter_rsp__free_unpacked
                     (Protocol__ParameterRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__parameter_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__parameter_req__field_descriptors[1] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__ParameterReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__parameter_req__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__parameter_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__parameter_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.ParameterReq",
  "ParameterReq",
  "Protocol__ParameterReq",
  "protocol",
  sizeof(Protocol__ParameterReq),
  1,
  protocol__parameter_req__field_descriptors,
  protocol__parameter_req__field_indices_by_name,
  1,  protocol__parameter_req__number_ranges,
  (ProtobufCMessageInit) protocol__parameter_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t protocol__parameter__env_sample_threshold__default_value = 0;
static const int32_t protocol__parameter__behavior_sample_threshold__default_value = 0;
static const int32_t protocol__parameter__gpssample_threshold__default_value = 0;
static const int32_t protocol__parameter__communication_threshold__default_value = 0;
static const int32_t protocol__parameter__estrus_sample_threshold__default_value = 0;
static const int32_t protocol__parameter__estrus_parameter_one__default_value = 0;
static const ProtobufCFieldDescriptor protocol__parameter__field_descriptors[10] =
{
  {
    "ServerHost",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Protocol__Parameter, n_serverhost),
    offsetof(Protocol__Parameter, serverhost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ServerPort",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, n_serverport),
    offsetof(Protocol__Parameter, serverport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SMSAlarmReceiverList",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Protocol__Parameter, n_smsalarmreceiverlist),
    offsetof(Protocol__Parameter, smsalarmreceiverlist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SMSWakeupWhiteList",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Protocol__Parameter, n_smswakeupwhitelist),
    offsetof(Protocol__Parameter, smswakeupwhitelist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EnvSampleThreshold",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, has_envsamplethreshold),
    offsetof(Protocol__Parameter, envsamplethreshold),
    NULL,
    &protocol__parameter__env_sample_threshold__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BehaviorSampleThreshold",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, has_behaviorsamplethreshold),
    offsetof(Protocol__Parameter, behaviorsamplethreshold),
    NULL,
    &protocol__parameter__behavior_sample_threshold__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSSampleThreshold",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, has_gpssamplethreshold),
    offsetof(Protocol__Parameter, gpssamplethreshold),
    NULL,
    &protocol__parameter__gpssample_threshold__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CommunicationThreshold",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, has_communicationthreshold),
    offsetof(Protocol__Parameter, communicationthreshold),
    NULL,
    &protocol__parameter__communication_threshold__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EstrusSampleThreshold",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, has_estrussamplethreshold),
    offsetof(Protocol__Parameter, estrussamplethreshold),
    NULL,
    &protocol__parameter__estrus_sample_threshold__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EstrusParameterOne",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Parameter, has_estrusparameterone),
    offsetof(Protocol__Parameter, estrusparameterone),
    NULL,
    &protocol__parameter__estrus_parameter_one__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__parameter__field_indices_by_name[] = {
  5,   /* field[5] = BehaviorSampleThreshold */
  7,   /* field[7] = CommunicationThreshold */
  4,   /* field[4] = EnvSampleThreshold */
  9,   /* field[9] = EstrusParameterOne */
  8,   /* field[8] = EstrusSampleThreshold */
  6,   /* field[6] = GPSSampleThreshold */
  2,   /* field[2] = SMSAlarmReceiverList */
  3,   /* field[3] = SMSWakeupWhiteList */
  0,   /* field[0] = ServerHost */
  1,   /* field[1] = ServerPort */
};
static const ProtobufCIntRange protocol__parameter__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 8 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor protocol__parameter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Parameter",
  "Parameter",
  "Protocol__Parameter",
  "protocol",
  sizeof(Protocol__Parameter),
  10,
  protocol__parameter__field_descriptors,
  protocol__parameter__field_indices_by_name,
  2,  protocol__parameter__number_ranges,
  (ProtobufCMessageInit) protocol__parameter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__parameter_rsp__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__ParameterRsp, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ParameterInfo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__ParameterRsp, parameterinfo),
    &protocol__parameter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__parameter_rsp__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
  1,   /* field[1] = ParameterInfo */
};
static const ProtobufCIntRange protocol__parameter_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__parameter_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.ParameterRsp",
  "ParameterRsp",
  "Protocol__ParameterRsp",
  "protocol",
  sizeof(Protocol__ParameterRsp),
  2,
  protocol__parameter_rsp__field_descriptors,
  protocol__parameter_rsp__field_indices_by_name,
  1,  protocol__parameter_rsp__number_ranges,
  (ProtobufCMessageInit) protocol__parameter_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
