/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Ping.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Ping.pb-c.h"
void   protocol__ping_req__init
                     (Protocol__PingReq         *message)
{
  static const Protocol__PingReq init_value = PROTOCOL__PING_REQ__INIT;
  *message = init_value;
}
size_t protocol__ping_req__get_packed_size
                     (const Protocol__PingReq *message)
{
  assert(message->base.descriptor == &protocol__ping_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__ping_req__pack
                     (const Protocol__PingReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__ping_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__ping_req__pack_to_buffer
                     (const Protocol__PingReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__ping_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__PingReq *
       protocol__ping_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__PingReq *)
     protobuf_c_message_unpack (&protocol__ping_req__descriptor,
                                allocator, len, data);
}
void   protocol__ping_req__free_unpacked
                     (Protocol__PingReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__ping_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__ping_resp__init
                     (Protocol__PingResp         *message)
{
  static const Protocol__PingResp init_value = PROTOCOL__PING_RESP__INIT;
  *message = init_value;
}
size_t protocol__ping_resp__get_packed_size
                     (const Protocol__PingResp *message)
{
  assert(message->base.descriptor == &protocol__ping_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__ping_resp__pack
                     (const Protocol__PingResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__ping_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__ping_resp__pack_to_buffer
                     (const Protocol__PingResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__ping_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__PingResp *
       protocol__ping_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__PingResp *)
     protobuf_c_message_unpack (&protocol__ping_resp__descriptor,
                                allocator, len, data);
}
void   protocol__ping_resp__free_unpacked
                     (Protocol__PingResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__ping_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__ping_req__field_descriptors[1] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__PingReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__ping_req__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__ping_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__ping_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.PingReq",
  "PingReq",
  "Protocol__PingReq",
  "protocol",
  sizeof(Protocol__PingReq),
  1,
  protocol__ping_req__field_descriptors,
  protocol__ping_req__field_indices_by_name,
  1,  protocol__ping_req__number_ranges,
  (ProtobufCMessageInit) protocol__ping_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__ping_resp__field_descriptors[1] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__PingResp, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__ping_resp__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__ping_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__ping_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.PingResp",
  "PingResp",
  "Protocol__PingResp",
  "protocol",
  sizeof(Protocol__PingResp),
  1,
  protocol__ping_resp__field_descriptors,
  protocol__ping_resp__field_indices_by_name,
  1,  protocol__ping_resp__number_ranges,
  (ProtobufCMessageInit) protocol__ping_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
