# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Ping.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\nPing.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\".\n\x07PingReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\"/\n\x08PingResp\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_PINGREQ = _descriptor.Descriptor(
  name='PingReq',
  full_name='protocol.PingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.PingReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=89,
)


_PINGRESP = _descriptor.Descriptor(
  name='PingResp',
  full_name='protocol.PingResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.PingResp.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=138,
)

_PINGREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_PINGRESP.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
DESCRIPTOR.message_types_by_name['PingReq'] = _PINGREQ
DESCRIPTOR.message_types_by_name['PingResp'] = _PINGRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQ,
  __module__ = 'Ping_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PingReq)
  ))
_sym_db.RegisterMessage(PingReq)

PingResp = _reflection.GeneratedProtocolMessageType('PingResp', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESP,
  __module__ = 'Ping_pb2'
  # @@protoc_insertion_point(class_scope:protocol.PingResp)
  ))
_sym_db.RegisterMessage(PingResp)


# @@protoc_insertion_point(module_scope)
