/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Register.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Register.pb-c.h"
void   protocol__register_req__init
                     (Protocol__RegisterReq         *message)
{
  static const Protocol__RegisterReq init_value = PROTOCOL__REGISTER_REQ__INIT;
  *message = init_value;
}
size_t protocol__register_req__get_packed_size
                     (const Protocol__RegisterReq *message)
{
  assert(message->base.descriptor == &protocol__register_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__register_req__pack
                     (const Protocol__RegisterReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__register_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__register_req__pack_to_buffer
                     (const Protocol__RegisterReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__register_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__RegisterReq *
       protocol__register_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__RegisterReq *)
     protobuf_c_message_unpack (&protocol__register_req__descriptor,
                                allocator, len, data);
}
void   protocol__register_req__free_unpacked
                     (Protocol__RegisterReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__register_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__register_rsp__init
                     (Protocol__RegisterRsp         *message)
{
  static const Protocol__RegisterRsp init_value = PROTOCOL__REGISTER_RSP__INIT;
  *message = init_value;
}
size_t protocol__register_rsp__get_packed_size
                     (const Protocol__RegisterRsp *message)
{
  assert(message->base.descriptor == &protocol__register_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__register_rsp__pack
                     (const Protocol__RegisterRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__register_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__register_rsp__pack_to_buffer
                     (const Protocol__RegisterRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__register_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__RegisterRsp *
       protocol__register_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__RegisterRsp *)
     protobuf_c_message_unpack (&protocol__register_rsp__descriptor,
                                allocator, len, data);
}
void   protocol__register_rsp__free_unpacked
                     (Protocol__RegisterRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__register_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char protocol__register_req__imei__default_value[] = "";
char protocol__register_req__mac__default_value[] = "";
static const int32_t protocol__register_req__device_type__default_value = 0;
static const int32_t protocol__register_req__hardware_version__default_value = 0;
static const int32_t protocol__register_req__firmware_version__default_value = 0;
static const int32_t protocol__register_req__status__default_value = 0;
static const int32_t protocol__register_req__battery_voltage__default_value = 0;
static const int32_t protocol__register_req__battery_power__default_value = 0;
static const int32_t protocol__register_req__signal_strength__default_value = 0;
static const int32_t protocol__register_req__bit_error_rate__default_value = 0;
static const int32_t protocol__register_req__radio_access_technology__default_value = 0;
static const uint32_t protocol__register_req__network_operator__default_value = 0u;
static const ProtobufCFieldDescriptor protocol__register_req__field_descriptors[14] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__RegisterReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IMSI",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__RegisterReq, imsi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IMEI",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__RegisterReq, imei),
    NULL,
    &protocol__register_req__imei__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MAC",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__RegisterReq, mac),
    NULL,
    &protocol__register_req__mac__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DeviceType",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_devicetype),
    offsetof(Protocol__RegisterReq, devicetype),
    NULL,
    &protocol__register_req__device_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HardwareVersion",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_hardwareversion),
    offsetof(Protocol__RegisterReq, hardwareversion),
    NULL,
    &protocol__register_req__hardware_version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FirmwareVersion",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_firmwareversion),
    offsetof(Protocol__RegisterReq, firmwareversion),
    NULL,
    &protocol__register_req__firmware_version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Status",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_status),
    offsetof(Protocol__RegisterReq, status),
    NULL,
    &protocol__register_req__status__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BatteryVoltage",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_batteryvoltage),
    offsetof(Protocol__RegisterReq, batteryvoltage),
    NULL,
    &protocol__register_req__battery_voltage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BatteryPower",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_batterypower),
    offsetof(Protocol__RegisterReq, batterypower),
    NULL,
    &protocol__register_req__battery_power__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SignalStrength",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_signalstrength),
    offsetof(Protocol__RegisterReq, signalstrength),
    NULL,
    &protocol__register_req__signal_strength__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BitErrorRate",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_biterrorrate),
    offsetof(Protocol__RegisterReq, biterrorrate),
    NULL,
    &protocol__register_req__bit_error_rate__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "RadioAccessTechnology",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterReq, has_radioaccesstechnology),
    offsetof(Protocol__RegisterReq, radioaccesstechnology),
    NULL,
    &protocol__register_req__radio_access_technology__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NetworkOperator",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__RegisterReq, has_networkoperator),
    offsetof(Protocol__RegisterReq, networkoperator),
    NULL,
    &protocol__register_req__network_operator__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__register_req__field_indices_by_name[] = {
  9,   /* field[9] = BatteryPower */
  8,   /* field[8] = BatteryVoltage */
  11,   /* field[11] = BitErrorRate */
  4,   /* field[4] = DeviceType */
  6,   /* field[6] = FirmwareVersion */
  5,   /* field[5] = HardwareVersion */
  2,   /* field[2] = IMEI */
  1,   /* field[1] = IMSI */
  0,   /* field[0] = Iden */
  3,   /* field[3] = MAC */
  13,   /* field[13] = NetworkOperator */
  12,   /* field[12] = RadioAccessTechnology */
  10,   /* field[10] = SignalStrength */
  7,   /* field[7] = Status */
};
static const ProtobufCIntRange protocol__register_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor protocol__register_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.RegisterReq",
  "RegisterReq",
  "Protocol__RegisterReq",
  "protocol",
  sizeof(Protocol__RegisterReq),
  14,
  protocol__register_req__field_descriptors,
  protocol__register_req__field_indices_by_name,
  1,  protocol__register_req__number_ranges,
  (ProtobufCMessageInit) protocol__register_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t protocol__register_rsp__sim_type__default_value = 0;
static const ProtobufCFieldDescriptor protocol__register_rsp__field_descriptors[3] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__RegisterRsp, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__RegisterRsp, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SimType",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__RegisterRsp, has_simtype),
    offsetof(Protocol__RegisterRsp, simtype),
    NULL,
    &protocol__register_rsp__sim_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__register_rsp__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
  2,   /* field[2] = SimType */
  1,   /* field[1] = Timestamp */
};
static const ProtobufCIntRange protocol__register_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__register_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.RegisterRsp",
  "RegisterRsp",
  "Protocol__RegisterRsp",
  "protocol",
  sizeof(Protocol__RegisterRsp),
  3,
  protocol__register_rsp__field_descriptors,
  protocol__register_rsp__field_indices_by_name,
  1,  protocol__register_rsp__number_ranges,
  (ProtobufCMessageInit) protocol__register_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
