# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Register.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Register.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0eRegister.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"\xe7\x02\n\x0bRegisterReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x0c\n\x04IMSI\x18\x02 \x02(\t\x12\x0e\n\x04IMEI\x18\x03 \x01(\t:\x00\x12\r\n\x03MAC\x18\x04 \x01(\t:\x00\x12\x15\n\nDeviceType\x18\x05 \x01(\x05:\x01\x30\x12\x1a\n\x0fHardwareVersion\x18\x06 \x01(\x05:\x01\x30\x12\x1a\n\x0f\x46irmwareVersion\x18\x07 \x01(\x05:\x01\x30\x12\x11\n\x06Status\x18\x08 \x01(\x05:\x01\x30\x12\x19\n\x0e\x42\x61tteryVoltage\x18\t \x01(\x05:\x01\x30\x12\x17\n\x0c\x42\x61tteryPower\x18\n \x01(\x05:\x01\x30\x12\x19\n\x0eSignalStrength\x18\x0b \x01(\x05:\x01\x30\x12\x17\n\x0c\x42itErrorRate\x18\x0c \x01(\x05:\x01\x30\x12 \n\x15RadioAccessTechnology\x18\r \x01(\x05:\x01\x30\x12\x1a\n\x0fNetworkOperator\x18\x0e \x01(\r:\x01\x30\"Y\n\x0bRegisterRsp\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x11\n\tTimestamp\x18\x02 \x02(\r\x12\x12\n\x07SimType\x18\x03 \x01(\x05:\x01\x30')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_REGISTERREQ = _descriptor.Descriptor(
  name='RegisterReq',
  full_name='protocol.RegisterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.RegisterReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IMSI', full_name='protocol.RegisterReq.IMSI', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IMEI', full_name='protocol.RegisterReq.IMEI', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MAC', full_name='protocol.RegisterReq.MAC', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DeviceType', full_name='protocol.RegisterReq.DeviceType', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HardwareVersion', full_name='protocol.RegisterReq.HardwareVersion', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FirmwareVersion', full_name='protocol.RegisterReq.FirmwareVersion', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Status', full_name='protocol.RegisterReq.Status', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatteryVoltage', full_name='protocol.RegisterReq.BatteryVoltage', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BatteryPower', full_name='protocol.RegisterReq.BatteryPower', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SignalStrength', full_name='protocol.RegisterReq.SignalStrength', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BitErrorRate', full_name='protocol.RegisterReq.BitErrorRate', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RadioAccessTechnology', full_name='protocol.RegisterReq.RadioAccessTechnology', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NetworkOperator', full_name='protocol.RegisterReq.NetworkOperator', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=407,
)


_REGISTERRSP = _descriptor.Descriptor(
  name='RegisterRsp',
  full_name='protocol.RegisterRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.RegisterRsp.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.RegisterRsp.Timestamp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SimType', full_name='protocol.RegisterRsp.SimType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=498,
)

_REGISTERREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_REGISTERRSP.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
DESCRIPTOR.message_types_by_name['RegisterReq'] = _REGISTERREQ
DESCRIPTOR.message_types_by_name['RegisterRsp'] = _REGISTERRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterReq = _reflection.GeneratedProtocolMessageType('RegisterReq', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERREQ,
  __module__ = 'Register_pb2'
  # @@protoc_insertion_point(class_scope:protocol.RegisterReq)
  ))
_sym_db.RegisterMessage(RegisterReq)

RegisterRsp = _reflection.GeneratedProtocolMessageType('RegisterRsp', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERRSP,
  __module__ = 'Register_pb2'
  # @@protoc_insertion_point(class_scope:protocol.RegisterRsp)
  ))
_sym_db.RegisterMessage(RegisterRsp)


# @@protoc_insertion_point(module_scope)
