# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Setting.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Setting.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\rSetting.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"1\n\nSettingReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\"\'\n\tTimeRange\x12\r\n\x05\x42\x65gin\x18\x01 \x02(\r\x12\x0b\n\x03\x45nd\x18\x02 \x02(\r\"\xc0\x05\n\x07Setting\x12\x18\n\rEnvSampleMode\x18\x01 \x01(\x05:\x01\x30\x12\x1c\n\x11\x45nvSampleInterval\x18\x02 \x01(\x05:\x01\x30\x12\x1d\n\x12\x42\x65haviorSampleMode\x18\x04 \x01(\x05:\x01\x30\x12!\n\x16\x42\x65haviorSampleInterval\x18\x05 \x01(\x05:\x01\x30\x12\x18\n\rGPSSampleMode\x18\x07 \x01(\x05:\x01\x30\x12\x1c\n\x11GPSSampleInterval\x18\x08 \x01(\x05:\x01\x30\x12\x1c\n\x11\x43ommunicationMode\x18\n \x01(\x05:\x01\x31\x12 \n\x15\x43ommunicationInterval\x18\x0b \x01(\x05:\x01\x30\x12 \n\x16\x43ommunicationTimeTable\x18\x0c \x01(\t:\x00\x12\x16\n\x0bResetDevice\x18\x10 \x01(\x05:\x01\x30\x12)\n\x0cPowerOffTime\x18\x11 \x03(\x0b\x32\x13.protocol.TimeRange\x12\x17\n\x0cPowerOffMode\x18\x12 \x01(\x05:\x01\x30\x12\x1d\n\x12OTAFirmwareVersion\x18\x16 \x01(\x05:\x01\x30\x12\x17\n\rOTAFirmwareID\x18\x17 \x01(\t:\x00\x12\x1a\n\x0fOTAForceUpgrade\x18\x18 \x01(\x05:\x01\x30\x12\x17\n\rOTAServerHost\x18\x19 \x01(\t:\x00\x12\x18\n\rOTAServerPort\x18\x1a \x01(\x05:\x01\x30\x12\x12\n\x07SMSMode\x18\x1b \x01(\x05:\x01\x30\x12\x16\n\x0bSMSInterval\x18\x1c \x01(\x05:\x01\x30\x12\x14\n\tAlarmMode\x18\x1d \x01(\x05:\x01\x30\x12\'\n\nOriginTime\x18! \x03(\x0b\x32\x13.protocol.TimeRange\x12\x15\n\nOriginMode\x18\" \x01(\x05:\x01\x30\x12\x1b\n\x10\x45strusSampleMode\x18# \x01(\x05:\x01\x30\x12\x1f\n\x14\x45strusSampleInterval\x18$ \x01(\x05:\x01\x30\"Y\n\nSettingRsp\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12&\n\x0bSettingInfo\x18\x02 \x01(\x0b\x32\x11.protocol.Setting')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_SETTINGREQ = _descriptor.Descriptor(
  name='SettingReq',
  full_name='protocol.SettingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.SettingReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=95,
)


_TIMERANGE = _descriptor.Descriptor(
  name='TimeRange',
  full_name='protocol.TimeRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Begin', full_name='protocol.TimeRange.Begin', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='End', full_name='protocol.TimeRange.End', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=136,
)


_SETTING = _descriptor.Descriptor(
  name='Setting',
  full_name='protocol.Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='EnvSampleMode', full_name='protocol.Setting.EnvSampleMode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EnvSampleInterval', full_name='protocol.Setting.EnvSampleInterval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BehaviorSampleMode', full_name='protocol.Setting.BehaviorSampleMode', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BehaviorSampleInterval', full_name='protocol.Setting.BehaviorSampleInterval', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSSampleMode', full_name='protocol.Setting.GPSSampleMode', index=4,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSSampleInterval', full_name='protocol.Setting.GPSSampleInterval', index=5,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CommunicationMode', full_name='protocol.Setting.CommunicationMode', index=6,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CommunicationInterval', full_name='protocol.Setting.CommunicationInterval', index=7,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CommunicationTimeTable', full_name='protocol.Setting.CommunicationTimeTable', index=8,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ResetDevice', full_name='protocol.Setting.ResetDevice', index=9,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PowerOffTime', full_name='protocol.Setting.PowerOffTime', index=10,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PowerOffMode', full_name='protocol.Setting.PowerOffMode', index=11,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OTAFirmwareVersion', full_name='protocol.Setting.OTAFirmwareVersion', index=12,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OTAFirmwareID', full_name='protocol.Setting.OTAFirmwareID', index=13,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OTAForceUpgrade', full_name='protocol.Setting.OTAForceUpgrade', index=14,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OTAServerHost', full_name='protocol.Setting.OTAServerHost', index=15,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OTAServerPort', full_name='protocol.Setting.OTAServerPort', index=16,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMSMode', full_name='protocol.Setting.SMSMode', index=17,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMSInterval', full_name='protocol.Setting.SMSInterval', index=18,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AlarmMode', full_name='protocol.Setting.AlarmMode', index=19,
      number=29, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OriginTime', full_name='protocol.Setting.OriginTime', index=20,
      number=33, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OriginMode', full_name='protocol.Setting.OriginMode', index=21,
      number=34, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstrusSampleMode', full_name='protocol.Setting.EstrusSampleMode', index=22,
      number=35, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EstrusSampleInterval', full_name='protocol.Setting.EstrusSampleInterval', index=23,
      number=36, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=843,
)


_SETTINGRSP = _descriptor.Descriptor(
  name='SettingRsp',
  full_name='protocol.SettingRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.SettingRsp.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SettingInfo', full_name='protocol.SettingRsp.SettingInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=845,
  serialized_end=934,
)

_SETTINGREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_SETTING.fields_by_name['PowerOffTime'].message_type = _TIMERANGE
_SETTING.fields_by_name['OriginTime'].message_type = _TIMERANGE
_SETTINGRSP.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_SETTINGRSP.fields_by_name['SettingInfo'].message_type = _SETTING
DESCRIPTOR.message_types_by_name['SettingReq'] = _SETTINGREQ
DESCRIPTOR.message_types_by_name['TimeRange'] = _TIMERANGE
DESCRIPTOR.message_types_by_name['Setting'] = _SETTING
DESCRIPTOR.message_types_by_name['SettingRsp'] = _SETTINGRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SettingReq = _reflection.GeneratedProtocolMessageType('SettingReq', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGREQ,
  __module__ = 'Setting_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SettingReq)
  ))
_sym_db.RegisterMessage(SettingReq)

TimeRange = _reflection.GeneratedProtocolMessageType('TimeRange', (_message.Message,), dict(
  DESCRIPTOR = _TIMERANGE,
  __module__ = 'Setting_pb2'
  # @@protoc_insertion_point(class_scope:protocol.TimeRange)
  ))
_sym_db.RegisterMessage(TimeRange)

Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), dict(
  DESCRIPTOR = _SETTING,
  __module__ = 'Setting_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Setting)
  ))
_sym_db.RegisterMessage(Setting)

SettingRsp = _reflection.GeneratedProtocolMessageType('SettingRsp', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGRSP,
  __module__ = 'Setting_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SettingRsp)
  ))
_sym_db.RegisterMessage(SettingRsp)


# @@protoc_insertion_point(module_scope)
