/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SettingAndParam.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SettingAndParam.pb-c.h"
void   protocol__setting_and_param_req__init
                     (Protocol__SettingAndParamReq         *message)
{
  static const Protocol__SettingAndParamReq init_value = PROTOCOL__SETTING_AND_PARAM_REQ__INIT;
  *message = init_value;
}
size_t protocol__setting_and_param_req__get_packed_size
                     (const Protocol__SettingAndParamReq *message)
{
  assert(message->base.descriptor == &protocol__setting_and_param_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__setting_and_param_req__pack
                     (const Protocol__SettingAndParamReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__setting_and_param_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__setting_and_param_req__pack_to_buffer
                     (const Protocol__SettingAndParamReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__setting_and_param_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__SettingAndParamReq *
       protocol__setting_and_param_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__SettingAndParamReq *)
     protobuf_c_message_unpack (&protocol__setting_and_param_req__descriptor,
                                allocator, len, data);
}
void   protocol__setting_and_param_req__free_unpacked
                     (Protocol__SettingAndParamReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__setting_and_param_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__setting_and_param_rsp__init
                     (Protocol__SettingAndParamRsp         *message)
{
  static const Protocol__SettingAndParamRsp init_value = PROTOCOL__SETTING_AND_PARAM_RSP__INIT;
  *message = init_value;
}
size_t protocol__setting_and_param_rsp__get_packed_size
                     (const Protocol__SettingAndParamRsp *message)
{
  assert(message->base.descriptor == &protocol__setting_and_param_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__setting_and_param_rsp__pack
                     (const Protocol__SettingAndParamRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__setting_and_param_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__setting_and_param_rsp__pack_to_buffer
                     (const Protocol__SettingAndParamRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__setting_and_param_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__SettingAndParamRsp *
       protocol__setting_and_param_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__SettingAndParamRsp *)
     protobuf_c_message_unpack (&protocol__setting_and_param_rsp__descriptor,
                                allocator, len, data);
}
void   protocol__setting_and_param_rsp__free_unpacked
                     (Protocol__SettingAndParamRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__setting_and_param_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__setting_and_param_req__field_descriptors[1] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SettingAndParamReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__setting_and_param_req__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__setting_and_param_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__setting_and_param_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.SettingAndParamReq",
  "SettingAndParamReq",
  "Protocol__SettingAndParamReq",
  "protocol",
  sizeof(Protocol__SettingAndParamReq),
  1,
  protocol__setting_and_param_req__field_descriptors,
  protocol__setting_and_param_req__field_indices_by_name,
  1,  protocol__setting_and_param_req__number_ranges,
  (ProtobufCMessageInit) protocol__setting_and_param_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__setting_and_param_rsp__field_descriptors[3] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SettingAndParamRsp, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SettingInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SettingAndParamRsp, settinginfo),
    &protocol__setting__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ParameterInfo",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SettingAndParamRsp, parameterinfo),
    &protocol__parameter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__setting_and_param_rsp__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
  2,   /* field[2] = ParameterInfo */
  1,   /* field[1] = SettingInfo */
};
static const ProtobufCIntRange protocol__setting_and_param_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__setting_and_param_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.SettingAndParamRsp",
  "SettingAndParamRsp",
  "Protocol__SettingAndParamRsp",
  "protocol",
  sizeof(Protocol__SettingAndParamRsp),
  3,
  protocol__setting_and_param_rsp__field_descriptors,
  protocol__setting_and_param_rsp__field_indices_by_name,
  1,  protocol__setting_and_param_rsp__number_ranges,
  (ProtobufCMessageInit) protocol__setting_and_param_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
