/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SimpleRsp.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SimpleRsp.pb-c.h"
void   protocol__simple_rsp__init
                     (Protocol__SimpleRsp         *message)
{
  static const Protocol__SimpleRsp init_value = PROTOCOL__SIMPLE_RSP__INIT;
  *message = init_value;
}
size_t protocol__simple_rsp__get_packed_size
                     (const Protocol__SimpleRsp *message)
{
  assert(message->base.descriptor == &protocol__simple_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__simple_rsp__pack
                     (const Protocol__SimpleRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__simple_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__simple_rsp__pack_to_buffer
                     (const Protocol__SimpleRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__simple_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__SimpleRsp *
       protocol__simple_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__SimpleRsp *)
     protobuf_c_message_unpack (&protocol__simple_rsp__descriptor,
                                allocator, len, data);
}
void   protocol__simple_rsp__free_unpacked
                     (Protocol__SimpleRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__simple_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__simple_rsp__field_descriptors[1] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SimpleRsp, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__simple_rsp__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
};
static const ProtobufCIntRange protocol__simple_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__simple_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.SimpleRsp",
  "SimpleRsp",
  "Protocol__SimpleRsp",
  "protocol",
  sizeof(Protocol__SimpleRsp),
  1,
  protocol__simple_rsp__field_descriptors,
  protocol__simple_rsp__field_indices_by_name,
  1,  protocol__simple_rsp__number_ranges,
  (ProtobufCMessageInit) protocol__simple_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
