/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SimpleRsp.proto */

#ifndef PROTOBUF_C_SimpleRsp_2eproto__INCLUDED
#define PROTOBUF_C_SimpleRsp_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IdentityMsg.pb-c.h"

typedef struct _Protocol__SimpleRsp Protocol__SimpleRsp;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__SimpleRsp
{
  ProtobufCMessage base;
  /*
   * 身份验证
   */
  Protocol__IdentityMsg *iden;
};
#define PROTOCOL__SIMPLE_RSP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__simple_rsp__descriptor) \
    , NULL }


/* Protocol__SimpleRsp methods */
void   protocol__simple_rsp__init
                     (Protocol__SimpleRsp         *message);
size_t protocol__simple_rsp__get_packed_size
                     (const Protocol__SimpleRsp   *message);
size_t protocol__simple_rsp__pack
                     (const Protocol__SimpleRsp   *message,
                      uint8_t             *out);
size_t protocol__simple_rsp__pack_to_buffer
                     (const Protocol__SimpleRsp   *message,
                      ProtobufCBuffer     *buffer);
Protocol__SimpleRsp *
       protocol__simple_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__simple_rsp__free_unpacked
                     (Protocol__SimpleRsp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__SimpleRsp_Closure)
                 (const Protocol__SimpleRsp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__simple_rsp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SimpleRsp_2eproto__INCLUDED */
