/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SMS.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "SMS.pb-c.h"
void   protocol__smsmsg__init
                     (Protocol__SMSMsg         *message)
{
  static const Protocol__SMSMsg init_value = PROTOCOL__SMSMSG__INIT;
  *message = init_value;
}
size_t protocol__smsmsg__get_packed_size
                     (const Protocol__SMSMsg *message)
{
  assert(message->base.descriptor == &protocol__smsmsg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__smsmsg__pack
                     (const Protocol__SMSMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__smsmsg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__smsmsg__pack_to_buffer
                     (const Protocol__SMSMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__smsmsg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__SMSMsg *
       protocol__smsmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__SMSMsg *)
     protobuf_c_message_unpack (&protocol__smsmsg__descriptor,
                                allocator, len, data);
}
void   protocol__smsmsg__free_unpacked
                     (Protocol__SMSMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__smsmsg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__smsrply__init
                     (Protocol__SMSRply         *message)
{
  static const Protocol__SMSRply init_value = PROTOCOL__SMSRPLY__INIT;
  *message = init_value;
}
size_t protocol__smsrply__get_packed_size
                     (const Protocol__SMSRply *message)
{
  assert(message->base.descriptor == &protocol__smsrply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__smsrply__pack
                     (const Protocol__SMSRply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__smsrply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__smsrply__pack_to_buffer
                     (const Protocol__SMSRply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__smsrply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__SMSRply *
       protocol__smsrply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__SMSRply *)
     protobuf_c_message_unpack (&protocol__smsrply__descriptor,
                                allocator, len, data);
}
void   protocol__smsrply__free_unpacked
                     (Protocol__SMSRply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__smsrply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char protocol__smsmsg__server_host__default_value[] = "";
static const int32_t protocol__smsmsg__server_port__default_value = 0;
static const int32_t protocol__smsmsg__gpsaction__default_value = 0;
static const protobuf_c_boolean protocol__smsmsg__send_sms__default_value = 0;
static const protobuf_c_boolean protocol__smsmsg__connect_server__default_value = 0;
static const protobuf_c_boolean protocol__smsmsg__connect_interval__default_value = 0;
static const int32_t protocol__smsmsg__connect_timeout__default_value = 0;
static const protobuf_c_boolean protocol__smsmsg__keep_online__default_value = 0;
static const int32_t protocol__smsmsg__keep_online_timeout__default_value = 0;
static const ProtobufCFieldDescriptor protocol__smsmsg__field_descriptors[10] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSMsg, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ServerHost",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSMsg, serverhost),
    NULL,
    &protocol__smsmsg__server_host__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ServerPort",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__SMSMsg, has_serverport),
    offsetof(Protocol__SMSMsg, serverport),
    NULL,
    &protocol__smsmsg__server_port__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSAction",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__SMSMsg, has_gpsaction),
    offsetof(Protocol__SMSMsg, gpsaction),
    NULL,
    &protocol__smsmsg__gpsaction__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SendSMS",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Protocol__SMSMsg, has_sendsms),
    offsetof(Protocol__SMSMsg, sendsms),
    NULL,
    &protocol__smsmsg__send_sms__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ConnectServer",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Protocol__SMSMsg, has_connectserver),
    offsetof(Protocol__SMSMsg, connectserver),
    NULL,
    &protocol__smsmsg__connect_server__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ConnectInterval",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Protocol__SMSMsg, has_connectinterval),
    offsetof(Protocol__SMSMsg, connectinterval),
    NULL,
    &protocol__smsmsg__connect_interval__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ConnectTimeout",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__SMSMsg, has_connecttimeout),
    offsetof(Protocol__SMSMsg, connecttimeout),
    NULL,
    &protocol__smsmsg__connect_timeout__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "KeepOnline",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Protocol__SMSMsg, has_keeponline),
    offsetof(Protocol__SMSMsg, keeponline),
    NULL,
    &protocol__smsmsg__keep_online__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "KeepOnlineTimeout",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__SMSMsg, has_keeponlinetimeout),
    offsetof(Protocol__SMSMsg, keeponlinetimeout),
    NULL,
    &protocol__smsmsg__keep_online_timeout__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__smsmsg__field_indices_by_name[] = {
  6,   /* field[6] = ConnectInterval */
  5,   /* field[5] = ConnectServer */
  7,   /* field[7] = ConnectTimeout */
  3,   /* field[3] = GPSAction */
  0,   /* field[0] = Iden */
  8,   /* field[8] = KeepOnline */
  9,   /* field[9] = KeepOnlineTimeout */
  4,   /* field[4] = SendSMS */
  1,   /* field[1] = ServerHost */
  2,   /* field[2] = ServerPort */
};
static const ProtobufCIntRange protocol__smsmsg__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor protocol__smsmsg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.SMSMsg",
  "SMSMsg",
  "Protocol__SMSMsg",
  "protocol",
  sizeof(Protocol__SMSMsg),
  10,
  protocol__smsmsg__field_descriptors,
  protocol__smsmsg__field_indices_by_name,
  2,  protocol__smsmsg__number_ranges,
  (ProtobufCMessageInit) protocol__smsmsg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char protocol__smsrply__peer_phone_number__default_value[] = "";
static const uint32_t protocol__smsrply__timestamp__default_value = 0u;
static const ProtobufCFieldDescriptor protocol__smsrply__field_descriptors[6] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSRply, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Timestamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__SMSRply, has_timestamp),
    offsetof(Protocol__SMSRply, timestamp),
    NULL,
    &protocol__smsrply__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PeerPhoneNumber",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSRply, peerphonenumber),
    NULL,
    &protocol__smsrply__peer_phone_number__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSInfo",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSRply, gpsinfo),
    &protocol__gps__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EnvInfo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSRply, envinfo),
    &protocol__env__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CellularInfo",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__SMSRply, cellularinfo),
    &protocol__cellular__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__smsrply__field_indices_by_name[] = {
  5,   /* field[5] = CellularInfo */
  4,   /* field[4] = EnvInfo */
  3,   /* field[3] = GPSInfo */
  0,   /* field[0] = Iden */
  2,   /* field[2] = PeerPhoneNumber */
  1,   /* field[1] = Timestamp */
};
static const ProtobufCIntRange protocol__smsrply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor protocol__smsrply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.SMSRply",
  "SMSRply",
  "Protocol__SMSRply",
  "protocol",
  sizeof(Protocol__SMSRply),
  6,
  protocol__smsrply__field_descriptors,
  protocol__smsrply__field_indices_by_name,
  1,  protocol__smsrply__number_ranges,
  (ProtobufCMessageInit) protocol__smsrply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
