# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SMS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2
import GPS_pb2 as GPS__pb2
import Env_pb2 as Env__pb2
import Cellular_pb2 as Cellular__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SMS.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\tSMS.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\x1a\tGPS.proto\x1a\tEnv.proto\x1a\x0e\x43\x65llular.proto\"\x9a\x02\n\x06SMSMsg\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x14\n\nServerHost\x18\x04 \x01(\t:\x00\x12\x15\n\nServerPort\x18\x05 \x01(\x05:\x01\x30\x12\x14\n\tGPSAction\x18\x06 \x01(\x05:\x01\x30\x12\x16\n\x07SendSMS\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x1c\n\rConnectServer\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x0f\x43onnectInterval\x18\t \x01(\x08:\x05\x66\x61lse\x12\x19\n\x0e\x43onnectTimeout\x18\n \x01(\x05:\x01\x30\x12\x19\n\nKeepOnline\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x1c\n\x11KeepOnlineTimeout\x18\x0c \x01(\x05:\x01\x30\"\xc9\x01\n\x07SMSRply\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x14\n\tTimestamp\x18\x02 \x01(\r:\x01\x30\x12\x19\n\x0fPeerPhoneNumber\x18\x03 \x01(\t:\x00\x12\x1e\n\x07GPSInfo\x18\x04 \x01(\x0b\x32\r.protocol.GPS\x12\x1e\n\x07\x45nvInfo\x18\x05 \x01(\x0b\x32\r.protocol.Env\x12(\n\x0c\x43\x65llularInfo\x18\x06 \x01(\x0b\x32\x12.protocol.Cellular')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,GPS__pb2.DESCRIPTOR,Env__pb2.DESCRIPTOR,Cellular__pb2.DESCRIPTOR,])




_SMSMSG = _descriptor.Descriptor(
  name='SMSMsg',
  full_name='protocol.SMSMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.SMSMsg.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ServerHost', full_name='protocol.SMSMsg.ServerHost', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ServerPort', full_name='protocol.SMSMsg.ServerPort', index=2,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSAction', full_name='protocol.SMSMsg.GPSAction', index=3,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SendSMS', full_name='protocol.SMSMsg.SendSMS', index=4,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ConnectServer', full_name='protocol.SMSMsg.ConnectServer', index=5,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ConnectInterval', full_name='protocol.SMSMsg.ConnectInterval', index=6,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ConnectTimeout', full_name='protocol.SMSMsg.ConnectTimeout', index=7,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='KeepOnline', full_name='protocol.SMSMsg.KeepOnline', index=8,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='KeepOnlineTimeout', full_name='protocol.SMSMsg.KeepOnlineTimeout', index=9,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=363,
)


_SMSRPLY = _descriptor.Descriptor(
  name='SMSRply',
  full_name='protocol.SMSRply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.SMSRply.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.SMSRply.Timestamp', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PeerPhoneNumber', full_name='protocol.SMSRply.PeerPhoneNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSInfo', full_name='protocol.SMSRply.GPSInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EnvInfo', full_name='protocol.SMSRply.EnvInfo', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CellularInfo', full_name='protocol.SMSRply.CellularInfo', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=567,
)

_SMSMSG.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_SMSRPLY.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_SMSRPLY.fields_by_name['GPSInfo'].message_type = GPS__pb2._GPS
_SMSRPLY.fields_by_name['EnvInfo'].message_type = Env__pb2._ENV
_SMSRPLY.fields_by_name['CellularInfo'].message_type = Cellular__pb2._CELLULAR
DESCRIPTOR.message_types_by_name['SMSMsg'] = _SMSMSG
DESCRIPTOR.message_types_by_name['SMSRply'] = _SMSRPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SMSMsg = _reflection.GeneratedProtocolMessageType('SMSMsg', (_message.Message,), dict(
  DESCRIPTOR = _SMSMSG,
  __module__ = 'SMS_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SMSMsg)
  ))
_sym_db.RegisterMessage(SMSMsg)

SMSRply = _reflection.GeneratedProtocolMessageType('SMSRply', (_message.Message,), dict(
  DESCRIPTOR = _SMSRPLY,
  __module__ = 'SMS_pb2'
  # @@protoc_insertion_point(class_scope:protocol.SMSRply)
  ))
_sym_db.RegisterMessage(SMSRply)


# @@protoc_insertion_point(module_scope)
