/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Status.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Status.pb-c.h"
void   protocol__status_req__init
                     (Protocol__StatusReq         *message)
{
  static const Protocol__StatusReq init_value = PROTOCOL__STATUS_REQ__INIT;
  *message = init_value;
}
size_t protocol__status_req__get_packed_size
                     (const Protocol__StatusReq *message)
{
  assert(message->base.descriptor == &protocol__status_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__status_req__pack
                     (const Protocol__StatusReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__status_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__status_req__pack_to_buffer
                     (const Protocol__StatusReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__status_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__StatusReq *
       protocol__status_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__StatusReq *)
     protobuf_c_message_unpack (&protocol__status_req__descriptor,
                                allocator, len, data);
}
void   protocol__status_req__free_unpacked
                     (Protocol__StatusReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__status_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__status__init
                     (Protocol__Status         *message)
{
  static const Protocol__Status init_value = PROTOCOL__STATUS__INIT;
  *message = init_value;
}
size_t protocol__status__get_packed_size
                     (const Protocol__Status *message)
{
  assert(message->base.descriptor == &protocol__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__status__pack
                     (const Protocol__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__status__pack_to_buffer
                     (const Protocol__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Status *
       protocol__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Status *)
     protobuf_c_message_unpack (&protocol__status__descriptor,
                                allocator, len, data);
}
void   protocol__status__free_unpacked
                     (Protocol__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__status_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__StatusReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StatusInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__StatusReq, n_statusinfo),
    offsetof(Protocol__StatusReq, statusinfo),
    &protocol__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__status_req__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
  1,   /* field[1] = StatusInfo */
};
static const ProtobufCIntRange protocol__status_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__status_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.StatusReq",
  "StatusReq",
  "Protocol__StatusReq",
  "protocol",
  sizeof(Protocol__StatusReq),
  2,
  protocol__status_req__field_descriptors,
  protocol__status_req__field_indices_by_name,
  1,  protocol__status_req__number_ranges,
  (ProtobufCMessageInit) protocol__status_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__status__timestamp__default_value = 0u;
static const uint32_t protocol__status__status_type__default_value = 0u;
static const uint32_t protocol__status__status_value__default_value = 0u;
static const uint32_t protocol__status__firmware_version__default_value = 0u;
static const int32_t protocol__status__voltage__default_value = 0;
static const ProtobufCFieldDescriptor protocol__status__field_descriptors[5] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Status, has_timestamp),
    offsetof(Protocol__Status, timestamp),
    NULL,
    &protocol__status__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StatusType",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Status, has_statustype),
    offsetof(Protocol__Status, statustype),
    NULL,
    &protocol__status__status_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StatusValue",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Status, has_statusvalue),
    offsetof(Protocol__Status, statusvalue),
    NULL,
    &protocol__status__status_value__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "FirmwareVersion",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Status, has_firmwareversion),
    offsetof(Protocol__Status, firmwareversion),
    NULL,
    &protocol__status__firmware_version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Voltage",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Protocol__Status, has_voltage),
    offsetof(Protocol__Status, voltage),
    NULL,
    &protocol__status__voltage__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__status__field_indices_by_name[] = {
  3,   /* field[3] = FirmwareVersion */
  1,   /* field[1] = StatusType */
  2,   /* field[2] = StatusValue */
  0,   /* field[0] = Timestamp */
  4,   /* field[4] = Voltage */
};
static const ProtobufCIntRange protocol__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protocol__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Status",
  "Status",
  "Protocol__Status",
  "protocol",
  sizeof(Protocol__Status),
  5,
  protocol__status__field_descriptors,
  protocol__status__field_indices_by_name,
  1,  protocol__status__number_ranges,
  (ProtobufCMessageInit) protocol__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
