# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Status.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0cStatus.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\"V\n\tStatusReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12$\n\nStatusInfo\x18\x02 \x03(\x0b\x32\x10.protocol.Status\"}\n\x06Status\x12\x14\n\tTimestamp\x18\x01 \x01(\r:\x01\x30\x12\x15\n\nStatusType\x18\x02 \x01(\r:\x01\x30\x12\x16\n\x0bStatusValue\x18\x03 \x01(\r:\x01\x30\x12\x1a\n\x0f\x46irmwareVersion\x18\x04 \x01(\r:\x01\x30\x12\x12\n\x07Voltage\x18\x05 \x01(\x05:\x01\x30')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,])




_STATUSREQ = _descriptor.Descriptor(
  name='StatusReq',
  full_name='protocol.StatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.StatusReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StatusInfo', full_name='protocol.StatusReq.StatusInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=131,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='protocol.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.Status.Timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StatusType', full_name='protocol.Status.StatusType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StatusValue', full_name='protocol.Status.StatusValue', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FirmwareVersion', full_name='protocol.Status.FirmwareVersion', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Voltage', full_name='protocol.Status.Voltage', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=258,
)

_STATUSREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_STATUSREQ.fields_by_name['StatusInfo'].message_type = _STATUS
DESCRIPTOR.message_types_by_name['StatusReq'] = _STATUSREQ
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusReq = _reflection.GeneratedProtocolMessageType('StatusReq', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREQ,
  __module__ = 'Status_pb2'
  # @@protoc_insertion_point(class_scope:protocol.StatusReq)
  ))
_sym_db.RegisterMessage(StatusReq)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'Status_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Status)
  ))
_sym_db.RegisterMessage(Status)


# @@protoc_insertion_point(module_scope)
