# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Upload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2
import Behavior_pb2 as Behavior__pb2
import Cellular_pb2 as Cellular__pb2
import Status_pb2 as Status__pb2
import Env_pb2 as Env__pb2
import GPS_pb2 as GPS__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Upload.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0cUpload.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\x1a\x0e\x42\x65havior.proto\x1a\x0e\x43\x65llular.proto\x1a\x0cStatus.proto\x1a\tEnv.proto\x1a\tGPS.proto\"\xf7\x01\n\tUploadReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12\x1e\n\x07\x45nvInfo\x18\x02 \x03(\x0b\x32\r.protocol.Env\x12(\n\x0c\x42\x65haviorInfo\x18\x03 \x03(\x0b\x32\x12.protocol.Behavior\x12\x1e\n\x07GPSInfo\x18\x04 \x03(\x0b\x32\r.protocol.GPS\x12$\n\nStatusInfo\x18\x05 \x03(\x0b\x32\x10.protocol.Status\x12(\n\x0c\x43\x65llularInfo\x18\x06 \x03(\x0b\x32\x12.protocol.Cellular\x12\x0b\n\x03SMS\x18\n \x01(\x05')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,Behavior__pb2.DESCRIPTOR,Cellular__pb2.DESCRIPTOR,Status__pb2.DESCRIPTOR,Env__pb2.DESCRIPTOR,GPS__pb2.DESCRIPTOR,])




_UPLOADREQ = _descriptor.Descriptor(
  name='UploadReq',
  full_name='protocol.UploadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.UploadReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EnvInfo', full_name='protocol.UploadReq.EnvInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BehaviorInfo', full_name='protocol.UploadReq.BehaviorInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSInfo', full_name='protocol.UploadReq.GPSInfo', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StatusInfo', full_name='protocol.UploadReq.StatusInfo', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CellularInfo', full_name='protocol.UploadReq.CellularInfo', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMS', full_name='protocol.UploadReq.SMS', index=6,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=361,
)

_UPLOADREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_UPLOADREQ.fields_by_name['EnvInfo'].message_type = Env__pb2._ENV
_UPLOADREQ.fields_by_name['BehaviorInfo'].message_type = Behavior__pb2._BEHAVIOR
_UPLOADREQ.fields_by_name['GPSInfo'].message_type = GPS__pb2._GPS
_UPLOADREQ.fields_by_name['StatusInfo'].message_type = Status__pb2._STATUS
_UPLOADREQ.fields_by_name['CellularInfo'].message_type = Cellular__pb2._CELLULAR
DESCRIPTOR.message_types_by_name['UploadReq'] = _UPLOADREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadReq = _reflection.GeneratedProtocolMessageType('UploadReq', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADREQ,
  __module__ = 'Upload_pb2'
  # @@protoc_insertion_point(class_scope:protocol.UploadReq)
  ))
_sym_db.RegisterMessage(UploadReq)


# @@protoc_insertion_point(module_scope)
