/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Upload.proto */

#ifndef PROTOBUF_C_Upload_2eproto__INCLUDED
#define PROTOBUF_C_Upload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IdentityMsg.pb-c.h"
#include "Behavior.pb-c.h"
#include "Cellular.pb-c.h"
#include "Status.pb-c.h"
#include "Env.pb-c.h"
#include "GPS.pb-c.h"

typedef struct _Protocol__UploadReq Protocol__UploadReq;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__UploadReq
{
  ProtobufCMessage base;
  /*
   * 身份验证
   */
  Protocol__IdentityMsg *iden;
  /*
   * 环境数据
   */
  size_t n_envinfo;
  Protocol__Env **envinfo;
  /*
   * 行为数据
   */
  size_t n_behaviorinfo;
  Protocol__Behavior **behaviorinfo;
  /*
   * 定位数据
   */
  size_t n_gpsinfo;
  Protocol__GPS **gpsinfo;
  /*
   * 状态数据
   */
  size_t n_statusinfo;
  Protocol__Status **statusinfo;
  /*
   * 网络信息
   */
  size_t n_cellularinfo;
  Protocol__Cellular **cellularinfo;
  /*
   * 是否短信回传
   */
  protobuf_c_boolean has_sms;
  int32_t sms;
};
#define PROTOCOL__UPLOAD_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__upload_req__descriptor) \
    , NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0, 0 }


/* Protocol__UploadReq methods */
void   protocol__upload_req__init
                     (Protocol__UploadReq         *message);
size_t protocol__upload_req__get_packed_size
                     (const Protocol__UploadReq   *message);
size_t protocol__upload_req__pack
                     (const Protocol__UploadReq   *message,
                      uint8_t             *out);
size_t protocol__upload_req__pack_to_buffer
                     (const Protocol__UploadReq   *message,
                      ProtobufCBuffer     *buffer);
Protocol__UploadReq *
       protocol__upload_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__upload_req__free_unpacked
                     (Protocol__UploadReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__UploadReq_Closure)
                 (const Protocol__UploadReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__upload_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Upload_2eproto__INCLUDED */
