/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Warning.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Warning.pb-c.h"
void   protocol__warning_req__init
                     (Protocol__WarningReq         *message)
{
  static const Protocol__WarningReq init_value = PROTOCOL__WARNING_REQ__INIT;
  *message = init_value;
}
size_t protocol__warning_req__get_packed_size
                     (const Protocol__WarningReq *message)
{
  assert(message->base.descriptor == &protocol__warning_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__warning_req__pack
                     (const Protocol__WarningReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__warning_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__warning_req__pack_to_buffer
                     (const Protocol__WarningReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__warning_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__WarningReq *
       protocol__warning_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__WarningReq *)
     protobuf_c_message_unpack (&protocol__warning_req__descriptor,
                                allocator, len, data);
}
void   protocol__warning_req__free_unpacked
                     (Protocol__WarningReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__warning_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__warning__init
                     (Protocol__Warning         *message)
{
  static const Protocol__Warning init_value = PROTOCOL__WARNING__INIT;
  *message = init_value;
}
size_t protocol__warning__get_packed_size
                     (const Protocol__Warning *message)
{
  assert(message->base.descriptor == &protocol__warning__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__warning__pack
                     (const Protocol__Warning *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__warning__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__warning__pack_to_buffer
                     (const Protocol__Warning *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__warning__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Warning *
       protocol__warning__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Warning *)
     protobuf_c_message_unpack (&protocol__warning__descriptor,
                                allocator, len, data);
}
void   protocol__warning__free_unpacked
                     (Protocol__Warning *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__warning__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__warning_req__field_descriptors[2] =
{
  {
    "Iden",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__WarningReq, iden),
    &protocol__identity_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "WarningInfo",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protocol__WarningReq, n_warninginfo),
    offsetof(Protocol__WarningReq, warninginfo),
    &protocol__warning__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__warning_req__field_indices_by_name[] = {
  0,   /* field[0] = Iden */
  1,   /* field[1] = WarningInfo */
};
static const ProtobufCIntRange protocol__warning_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__warning_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.WarningReq",
  "WarningReq",
  "Protocol__WarningReq",
  "protocol",
  sizeof(Protocol__WarningReq),
  2,
  protocol__warning_req__field_descriptors,
  protocol__warning_req__field_indices_by_name,
  1,  protocol__warning_req__number_ranges,
  (ProtobufCMessageInit) protocol__warning_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t protocol__warning__timestamp__default_value = 0u;
static const Protocol__WarningType protocol__warning__type__default_value = PROTOCOL__WARNING_TYPE__WarningTypeUnknown;
static const ProtobufCFieldDescriptor protocol__warning__field_descriptors[4] =
{
  {
    "Timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Protocol__Warning, has_timestamp),
    offsetof(Protocol__Warning, timestamp),
    NULL,
    &protocol__warning__timestamp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Protocol__Warning, has_type),
    offsetof(Protocol__Warning, type),
    &protocol__warning_type__descriptor,
    &protocol__warning__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "EnvInfo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__Warning, envinfo),
    &protocol__env__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GPSInfo",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protocol__Warning, gpsinfo),
    &protocol__gps__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__warning__field_indices_by_name[] = {
  2,   /* field[2] = EnvInfo */
  3,   /* field[3] = GPSInfo */
  0,   /* field[0] = Timestamp */
  1,   /* field[1] = Type */
};
static const ProtobufCIntRange protocol__warning__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protocol__warning__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Warning",
  "Warning",
  "Protocol__Warning",
  "protocol",
  sizeof(Protocol__Warning),
  4,
  protocol__warning__field_descriptors,
  protocol__warning__field_indices_by_name,
  2,  protocol__warning__number_ranges,
  (ProtobufCMessageInit) protocol__warning__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue protocol__warning_type__enum_values_by_number[10] =
{
  { "WarningTypeUnknown", "PROTOCOL__WARNING_TYPE__WarningTypeUnknown", 1 },
  { "WarningTypeBoot", "PROTOCOL__WARNING_TYPE__WarningTypeBoot", 2 },
  { "WarningTypeLowBattery", "PROTOCOL__WARNING_TYPE__WarningTypeLowBattery", 3 },
  { "WarningTypeStatic", "PROTOCOL__WARNING_TYPE__WarningTypeStatic", 4 },
  { "WarningTypeGeoFenceIn", "PROTOCOL__WARNING_TYPE__WarningTypeGeoFenceIn", 5 },
  { "WarningTypeGeoFenceOut", "PROTOCOL__WARNING_TYPE__WarningTypeGeoFenceOut", 6 },
  { "WarningTypeDeviceRemove", "PROTOCOL__WARNING_TYPE__WarningTypeDeviceRemove", 7 },
  { "WarningTypeActivityExcess", "PROTOCOL__WARNING_TYPE__WarningTypeActivityExcess", 8 },
  { "WarningTypeTemperatureExcess", "PROTOCOL__WARNING_TYPE__WarningTypeTemperatureExcess", 9 },
  { "WarningTypeDeviceDestroy", "PROTOCOL__WARNING_TYPE__WarningTypeDeviceDestroy", 10 },
};
static const ProtobufCIntRange protocol__warning_type__value_ranges[] = {
{1, 0},{0, 10}
};
static const ProtobufCEnumValueIndex protocol__warning_type__enum_values_by_name[10] =
{
  { "WarningTypeActivityExcess", 7 },
  { "WarningTypeBoot", 1 },
  { "WarningTypeDeviceDestroy", 9 },
  { "WarningTypeDeviceRemove", 6 },
  { "WarningTypeGeoFenceIn", 4 },
  { "WarningTypeGeoFenceOut", 5 },
  { "WarningTypeLowBattery", 2 },
  { "WarningTypeStatic", 3 },
  { "WarningTypeTemperatureExcess", 8 },
  { "WarningTypeUnknown", 0 },
};
const ProtobufCEnumDescriptor protocol__warning_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "protocol.WarningType",
  "WarningType",
  "Protocol__WarningType",
  "protocol",
  10,
  protocol__warning_type__enum_values_by_number,
  10,
  protocol__warning_type__enum_values_by_name,
  1,
  protocol__warning_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
