# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Warning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IdentityMsg_pb2 as IdentityMsg__pb2
import GPS_pb2 as GPS__pb2
import Env_pb2 as Env__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Warning.proto',
  package='protocol',
  syntax='proto2',
  serialized_pb=_b('\n\rWarning.proto\x12\x08protocol\x1a\x11IdentityMsg.proto\x1a\tGPS.proto\x1a\tEnv.proto\"Y\n\nWarningReq\x12#\n\x04Iden\x18\x01 \x02(\x0b\x32\x15.protocol.IdentityMsg\x12&\n\x0bWarningInfo\x18\x02 \x03(\x0b\x32\x11.protocol.Warning\"\x98\x01\n\x07Warning\x12\x14\n\tTimestamp\x18\x01 \x01(\r:\x01\x30\x12\x37\n\x04Type\x18\x02 \x01(\x0e\x32\x15.protocol.WarningType:\x12WarningTypeUnknown\x12\x1e\n\x07\x45nvInfo\x18\x05 \x01(\x0b\x32\r.protocol.Env\x12\x1e\n\x07GPSInfo\x18\x06 \x01(\x0b\x32\r.protocol.GPS*\x9f\x02\n\x0bWarningType\x12\x16\n\x12WarningTypeUnknown\x10\x01\x12\x13\n\x0fWarningTypeBoot\x10\x02\x12\x19\n\x15WarningTypeLowBattery\x10\x03\x12\x15\n\x11WarningTypeStatic\x10\x04\x12\x19\n\x15WarningTypeGeoFenceIn\x10\x05\x12\x1a\n\x16WarningTypeGeoFenceOut\x10\x06\x12\x1b\n\x17WarningTypeDeviceRemove\x10\x07\x12\x1d\n\x19WarningTypeActivityExcess\x10\x08\x12 \n\x1cWarningTypeTemperatureExcess\x10\t\x12\x1c\n\x18WarningTypeDeviceDestroy\x10\n')
  ,
  dependencies=[IdentityMsg__pb2.DESCRIPTOR,GPS__pb2.DESCRIPTOR,Env__pb2.DESCRIPTOR,])

_WARNINGTYPE = _descriptor.EnumDescriptor(
  name='WarningType',
  full_name='protocol.WarningType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WarningTypeUnknown', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeBoot', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeLowBattery', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeStatic', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeGeoFenceIn', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeGeoFenceOut', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeDeviceRemove', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeActivityExcess', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeTemperatureExcess', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WarningTypeDeviceDestroy', index=9, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=315,
  serialized_end=602,
)
_sym_db.RegisterEnumDescriptor(_WARNINGTYPE)

WarningType = enum_type_wrapper.EnumTypeWrapper(_WARNINGTYPE)
WarningTypeUnknown = 1
WarningTypeBoot = 2
WarningTypeLowBattery = 3
WarningTypeStatic = 4
WarningTypeGeoFenceIn = 5
WarningTypeGeoFenceOut = 6
WarningTypeDeviceRemove = 7
WarningTypeActivityExcess = 8
WarningTypeTemperatureExcess = 9
WarningTypeDeviceDestroy = 10



_WARNINGREQ = _descriptor.Descriptor(
  name='WarningReq',
  full_name='protocol.WarningReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Iden', full_name='protocol.WarningReq.Iden', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WarningInfo', full_name='protocol.WarningReq.WarningInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=157,
)


_WARNING = _descriptor.Descriptor(
  name='Warning',
  full_name='protocol.Warning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='protocol.Warning.Timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Type', full_name='protocol.Warning.Type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EnvInfo', full_name='protocol.Warning.EnvInfo', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='GPSInfo', full_name='protocol.Warning.GPSInfo', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=312,
)

_WARNINGREQ.fields_by_name['Iden'].message_type = IdentityMsg__pb2._IDENTITYMSG
_WARNINGREQ.fields_by_name['WarningInfo'].message_type = _WARNING
_WARNING.fields_by_name['Type'].enum_type = _WARNINGTYPE
_WARNING.fields_by_name['EnvInfo'].message_type = Env__pb2._ENV
_WARNING.fields_by_name['GPSInfo'].message_type = GPS__pb2._GPS
DESCRIPTOR.message_types_by_name['WarningReq'] = _WARNINGREQ
DESCRIPTOR.message_types_by_name['Warning'] = _WARNING
DESCRIPTOR.enum_types_by_name['WarningType'] = _WARNINGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WarningReq = _reflection.GeneratedProtocolMessageType('WarningReq', (_message.Message,), dict(
  DESCRIPTOR = _WARNINGREQ,
  __module__ = 'Warning_pb2'
  # @@protoc_insertion_point(class_scope:protocol.WarningReq)
  ))
_sym_db.RegisterMessage(WarningReq)

Warning = _reflection.GeneratedProtocolMessageType('Warning', (_message.Message,), dict(
  DESCRIPTOR = _WARNING,
  __module__ = 'Warning_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Warning)
  ))
_sym_db.RegisterMessage(Warning)


# @@protoc_insertion_point(module_scope)
