/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Warning.proto */

#ifndef PROTOBUF_C_Warning_2eproto__INCLUDED
#define PROTOBUF_C_Warning_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "IdentityMsg.pb-c.h"
#include "GPS.pb-c.h"
#include "Env.pb-c.h"

typedef struct _Protocol__WarningReq Protocol__WarningReq;
typedef struct _Protocol__Warning Protocol__Warning;


/* --- enums --- */

typedef enum _Protocol__WarningType {
  /*
   * 未知类型报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeUnknown = 1,
  /*
   * 开机报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeBoot = 2,
  /*
   * 低电量报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeLowBattery = 3,
  /*
   * 静止报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeStatic = 4,
  /*
   * 进入围栏报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeGeoFenceIn = 5,
  /*
   * 离开围栏报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeGeoFenceOut = 6,
  /*
   * 拆除设备报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeDeviceRemove = 7,
  /*
   * 运动量过量
   */
  PROTOCOL__WARNING_TYPE__WarningTypeActivityExcess = 8,
  /*
   * 温度超标
   */
  PROTOCOL__WARNING_TYPE__WarningTypeTemperatureExcess = 9,
  /*
   * 开盖报警
   */
  PROTOCOL__WARNING_TYPE__WarningTypeDeviceDestroy = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTOCOL__WARNING_TYPE)
} Protocol__WarningType;

/* --- messages --- */

/*
 * 请求上传报警信息
 */
struct  _Protocol__WarningReq
{
  ProtobufCMessage base;
  Protocol__IdentityMsg *iden;
  size_t n_warninginfo;
  Protocol__Warning **warninginfo;
};
#define PROTOCOL__WARNING_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__warning_req__descriptor) \
    , NULL, 0,NULL }


struct  _Protocol__Warning
{
  ProtobufCMessage base;
  protobuf_c_boolean has_timestamp;
  uint32_t timestamp;
  protobuf_c_boolean has_type;
  Protocol__WarningType type;
  Protocol__Env *envinfo;
  Protocol__GPS *gpsinfo;
};
#define PROTOCOL__WARNING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__warning__descriptor) \
    , 0, 0u, 0, PROTOCOL__WARNING_TYPE__WarningTypeUnknown, NULL, NULL }


/* Protocol__WarningReq methods */
void   protocol__warning_req__init
                     (Protocol__WarningReq         *message);
size_t protocol__warning_req__get_packed_size
                     (const Protocol__WarningReq   *message);
size_t protocol__warning_req__pack
                     (const Protocol__WarningReq   *message,
                      uint8_t             *out);
size_t protocol__warning_req__pack_to_buffer
                     (const Protocol__WarningReq   *message,
                      ProtobufCBuffer     *buffer);
Protocol__WarningReq *
       protocol__warning_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__warning_req__free_unpacked
                     (Protocol__WarningReq *message,
                      ProtobufCAllocator *allocator);
/* Protocol__Warning methods */
void   protocol__warning__init
                     (Protocol__Warning         *message);
size_t protocol__warning__get_packed_size
                     (const Protocol__Warning   *message);
size_t protocol__warning__pack
                     (const Protocol__Warning   *message,
                      uint8_t             *out);
size_t protocol__warning__pack_to_buffer
                     (const Protocol__Warning   *message,
                      ProtobufCBuffer     *buffer);
Protocol__Warning *
       protocol__warning__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__warning__free_unpacked
                     (Protocol__Warning *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__WarningReq_Closure)
                 (const Protocol__WarningReq *message,
                  void *closure_data);
typedef void (*Protocol__Warning_Closure)
                 (const Protocol__Warning *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    protocol__warning_type__descriptor;
extern const ProtobufCMessageDescriptor protocol__warning_req__descriptor;
extern const ProtobufCMessageDescriptor protocol__warning__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Warning_2eproto__INCLUDED */
